act_code: '187744'
requisite: Решение маслихата района Ақсуат области Абай от 11 октября 2023 года № 7/5-VIII. Зарегистрировано Департаментом юстиции области Абай 30 октября 2023 года № 139-18. Утратило силу решением маслихата района Аксуат области Абай от 24 апреля 2024 года № 15/22-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в районе Аксуат
  kaz: Ақсуат ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-11
approved_by:
- '168004000002'
version_date:
  kaz: 2023-10-11
  rus: 2023-10-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/187744/kaz/11.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187744/rus/11.10.2023
