act_code: '189929'
requisite: Решение Абайского районного маслихата области Абай от 29 ноября 2023 года № 10/17-VIII. Зарегистрировано Департаментом юстиции области Абай 11 декабря 2023 года № 183-18. Утратило силу решением Абайского районного маслихата области Абай от 31 декабря 2024 года № 24/11-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания  социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-29
approved_by:
- '168005000002'
version_date:
  kaz: 2023-11-29
  rus: 2023-11-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/189929/kaz/29.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189929/rus/29.11.2023
