act_code: '188784'
requisite: Решение Бескарагайского районного маслихата области Абай от 14 ноября 2023 года № 9/15-VIII. Зарегистрировано Департаментом юстиции области Абай 22 ноября 2023 года № 158-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в Бескарагайском районе
  kaz: Бесқарағай ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-14
approved_by:
- '168007000002'
version_date:
  kaz: 2023-11-14
  rus: 2023-11-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/188784/kaz/14.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188784/rus/14.11.2023
