act_code: '205987'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2024 года № 23-2
title:
  rus: О Кокпектинском районном бюджете на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Көкпекті аудандық бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205987/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205987/rus/27.12.2024
