act_code: '192125'
requisite: Решение Урджарского районного маслихата области Абай от 26 декабря 2023 года № 9-216/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Коныршаулинского сельского округа Урджарского района на 2024-2026 годы
  kaz: Үржар ауданы Қоңыршәулі ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '168010000002'
version_date:
  kaz: 2024-07-17
  rus: 2024-07-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/192125/kaz/17.07.2024
  rus: https://zan.gov.kz/client/#!/doc/192125/rus/17.07.2024
caused_by:
  code: '198951'
  requisite: Решение Урджарского районного маслихата области Абай от 17 июля 2024 года № 15-323/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
  title:
    rus: О внесении изменения в решение Урджарского районного маслихата от 26 декабря 2023 года № 9-216/VIIІ «О бюджете Коныршаулинского сельского округа Урджарского района на 2024-2026 годы»
    kaz: Үржар аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 9-216/VIII «Үржар ауданы Қоңыршәулі ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/198951/rus
