act_code: '206235'
requisite: Решение Аягозского районного маслихата области Абай от 30 декабря 2024 года № 20/385-VIII
title:
  rus: О бюджете города Аягоз Аягозского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Аягөз ауданының Аягөз қаласының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168006000002'
version_date:
  kaz: 2025-07-14
  rus: 2025-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/206235/kaz/14.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206235/rus/14.07.2025
caused_by:
  code: '212488'
  requisite: Решение Аягозского районного маслихата области Абай от 14 июля 2025 года № 27/466-VIII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 30 декабря 2024 года № 20/385-VІIІ «О бюджете города Аягоз Аягозского района на 2025-2027 годы»
    kaz: Аягөз аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 20/385-VІІІ «2025-2027 жылдарға арналған Аягөз ауданының Аягөз қаласының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212488/rus
