act_code: '205998'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2024 года № 23-11
title:
  rus: О бюджете Шугылбайского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Шұғылбай ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2025-02-28
  rus: 2025-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205998/kaz/28.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205998/rus/28.02.2025
caused_by:
  code: '207858'
  requisite: Решение Кокпектинского районного маслихата области Абай от 28 февраля 2025 года № 25-10
  title:
    rus: О внесении изменений в решение Кокпектинского районного маслихата от 27 декабря 2024 года № 23-11 «О бюджете Шугылбайского сельского округа на 2025-2027 годы»
    kaz: Көкпекті аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 23-11 «2025-2027 жылдарға арналған Шұғылбай ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207858/rus
