act_code: '219964'
requisite: Решение маслихата района Жаңасемей области Абай от 18 декабря 2025 года № 23/275-VIII
title:
  rus: О бюджете района Жаңасемей на 2026–2028 год
  kaz: Жаңасемей ауданының 2026–2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '168013000002'
version_date:
  kaz: 2025-12-18
  rus: 2025-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/219964/kaz/18.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219964/rus/18.12.2025
