act_code: '198975'
requisite: Решение маслихата района Мақаншы области Абай от 18 июля 2024 года № 7-33/VIII. Утратило силу решением маслихата района Мақаншы области Абай от 30 декабря 2024 года № 16-112/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете района Мақаншы на 2024-2026 годы
  kaz: Мақаншы ауданының 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-18
approved_by:
- '168012000002'
version_date:
  kaz: 2024-09-27
  rus: 2024-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/198975/kaz/27.09.2024
  rus: https://zan.gov.kz/client/#!/doc/198975/rus/27.09.2024
caused_by:
  code: '201049'
  requisite: Решение маслихата района Мақаншы области Абай от 27 сентября 2024 года № 11-59/VIII. Утратило силу решением маслихата района Мақаншы области Абай от 30 декабря 2024 года № 16-112/VIII (вводится в действие с 01.01.2025)
  title:
    rus: О внесении изменений в решение маслихата района Мақаншы «О бюджете района Мақаншы на 2024-2026 годы» от 18 июля 2024 года № 7-33/VIII
    kaz: Мақаншы ауданы мәслихатының 2024 жылғы 18 шілдедегі № 7-33/VIII «Мақаншы ауданының 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201049/rus
