act_code: '220239'
requisite: Решение маслихата района Жаңасемей области Абай от 23 декабря 2025 года № 24/295-VIII
title:
  rus: О бюджете поселка Шульбинск района Жаңасемей области Абай на 2026-2028 годы
  kaz: Абай облысы Жаңасемей ауданы Шүлбі кентінің 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '168013000002'
version_date:
  kaz: 2026-09-02
  rus: 2026-09-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/220239/kaz/02.09.2026
  rus: https://zan.gov.kz/client/#!/doc/220239/rus/02.09.2026
caused_by:
  code: '229674'
  requisite: Решение маслихата района Жаңасемей области Абай от 2 сентября 2026 года № 30/371-VIII
  title:
    rus: О внесении изменений в решение маслихата района Жанасемей от 23 декабря 2025 года № 24/295-VIII «О бюджете поселка Шульбинск района Жанасемей области Абай на 2026-2028 годы»
    kaz: Жаңасемей аудандық маслихатының 2025 жылғы 23 желтоқсандағы № 24/295-VIII «Абай облысы Жаңасемей ауданы Шүлбі кентінің 2026-2028 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229674/rus
