act_code: '177923'
requisite: Решение Аягозского районного маслихата области Абай от 27 декабря 2022 года № 20/413-VII
title:
  rus: О бюджете Майлинского сельского округа Аягозского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Аягөз ауданының Майлин ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '168006000002'
version_date:
  kaz: 2022-12-27
  rus: 2022-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/177923/kaz/27.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177923/rus/27.12.2022
