act_code: '172443'
requisite: Решение маслихата района Ақсуат области Абай от 15 сентября 2022 года № 7/2-VII
title:
  rus: О бюджете района Ақсуат на 2022 - 2024 годы
  kaz: 2022-2024 жылдарға арналған Ақсуат ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-15
approved_by:
- '168004000002'
version_date:
  kaz: 2022-10-28
  rus: 2022-10-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/172443/kaz/28.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172443/rus/28.10.2022
caused_by:
  code: '173849'
  requisite: Решение маслихата района Ақсуат области Абай от 28 октября 2022 года № 9/2-VII
  title:
    rus: О внесении изменений и дополнении в решение маслихата района Ақсуат области Абай от 15 сентября 2022 года № 7/2-VII «О бюджете района Ақсуат на 2022 - 2024 годы»
    kaz: Абай облысы Ақсуат аудандық мәслихатының 2022 жылғы 15 қыркүйектегі № 7/2-VII «2022-2024 жылдарға арналған Ақсуат ауданының бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/173849/rus
