act_code: '203625'
requisite: Решение маслихата города Семей области Абай от 20 ноября 2024 года № 34/180-VIII. Зарегистрировано Департаментом юстиции области Абай 25 ноября 2024 года № 375-18
title:
  rus: О признании утратившим силу решения маслихата города Семей Восточно-Казахстанской области от 29 июля 2022 года № 27/215-VII «Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Семей»
  kaz: Шығыс Қазақстан облысы Семей қаласы мәслихатының 2022 жылғы 29 шілдедегі № 27/215-VII «Семей қаласы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-20
approved_by:
- '168002000002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/203625/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203625/rus/20.11.2024
