act_code: '193527'
requisite: Решение акима Жарминского района области Абай от 21 февраля 2024 года № 6. Утратило силу решением акима Жарминского района области Абай от 20 марта 2024 года № 8 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации
  kaz: Төтенше жағдайды жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-21
approved_by:
- '168009000003'
version_date:
  kaz: 2024-02-21
  rus: 2024-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/193527/kaz/21.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193527/rus/21.02.2024
