act_code: '220290'
requisite: Решение Урджарского районного маслихата области Абай от 18 декабря 2025 года № 31-615/VIII
title:
  rus: О бюджете Урджарского района на 2026-2028 годы
  kaz: Үржар ауданының 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '168010000002'
version_date:
  kaz: 2026-08-04
  rus: 2026-08-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/220290/kaz/04.08.2026
  rus: https://zan.gov.kz/client/#!/doc/220290/rus/04.08.2026
caused_by:
  code: '228464'
  requisite: Решение Урджарского районного маслихата области Абай от 4 августа 2026 года № 37-733/VIII
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 18 декабря 2025 года № 31-615/VIII «О бюджете Урджарского района на 2026-2028 годы»
    kaz: Үржар аудандық мәслихатының 2025 жылғы 18 желтоқсандағы № 31-615/VIII «Үржар ауданының 2026-2028 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228464/rus
