act_code: '212786'
requisite: Решение акима Шалабайского сельского округа Жарминского района области Абай от 23 июля 2025 года № 5
title:
  rus: О переименовании улицы села Шалабай Жарминского района области Абай
  kaz: Абай облысы Жарма ауданы Шалабай ауылындағы көшенің қайта атауы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-23
approved_by:
- '168009021002'
version_date:
  kaz: 2025-07-23
  rus: 2025-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/212786/kaz/23.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212786/rus/23.07.2025
