act_code: '213004'
requisite: Решение акима города Шар Жарминского района области Абай от 23 июля 2025 года № 5
title:
  rus: О переименовании улиц города Шар Жарминского района области Абай
  kaz: Абай облысы Жарма ауданы Шар қаласындағы көшелерді қайта атауы туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-23
approved_by:
- '168009022002'
version_date:
  kaz: 2025-07-23
  rus: 2025-07-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/213004/kaz/23.07.2025
  rus: https://zan.gov.kz/client/#!/doc/213004/rus/23.07.2025
