act_code: '188488'
requisite: Решение маслихата области Абай от 15 ноября 2023 года № 9/65-VIIІ
title:
  rus: Об утверждении Правил создания, содержания и защиты зеленых насаждений населенных пунктов области Абай
  kaz: Абай облысының елді мекендердің жасыл екпелерін жасау, күтіп-баптау және қорғау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-11-15
approved_by:
- '168000000002'
version_date:
  kaz: 2023-11-15
  rus: 2023-11-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/188488/kaz/15.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188488/rus/15.11.2023
