act_code: '205359'
requisite: Решение маслихата района Жаңасемей области Абай от 30 декабря 2024 года № 14/97-VIII
title:
  rus: О бюджете района Жаңасемей области Абай на 2025–2027 годы
  kaz: Абай облысы Жаңасемей ауданының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168013000002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/205359/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205359/rus/08.09.2025
caused_by:
  code: '214102'
  requisite: Решение маслихата района Жаңасемей области Абай от 8 сентября 2025 года № 19/203-VIII
  title:
    rus: О внесении изменений в решение маслихата района Жаңасемей от 30 декабря 2024 года № 14/97-VIII «О бюджете района Жаңасемей на 2025-2027 годы»
    kaz: Жаңасемей аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 14/97-VІII «Жаңасемей ауданының 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214102/rus
