act_code: '203197'
requisite: Решение акима М-Владимировского сельского округа Бескарагайского района области Абай от 25 ноября 2024 года № 4. Утратило силу решением акима М-Владимировского сельского округа Бескарагайского района области Абай от 20 января 2025 года № 1 (вводится в действие со дня его первого официального опубликования)
title:
  rus: О переименовании улиц села Малая Владимировка и села Бозтал Маловладимировского сельского округа Бескарагайского района области Абай
  kaz: Абай облысы Бесқарағай ауданы Малая Владимировка ауылдық округінің Малая Владимировка ауылының және Бозтал ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-25
approved_by:
- '168007007002'
version_date:
  kaz: 2024-11-25
  rus: 2024-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/203197/kaz/25.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203197/rus/25.11.2024
