act_code: '225481'
requisite: Решение акима Урджарского сельского округа Урджарского района области Абай от 8 мая 2026 года № 43
title:
  rus: О переименовании улицы села Урджар Урджарского сельского округа Урджарского района области Абай
  kaz: Абай облысы Үржар ауданы Үржар ауылдық округі Үржар ауылының көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-08
approved_by:
- '168010001002'
version_date:
  kaz: 2026-05-08
  rus: 2026-05-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/225481/kaz/08.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225481/rus/08.05.2026
