act_code: '190274'
requisite: Решение маслихата района Ақсуат области Абай от 5 декабря 2023 года № 8/4-VIII. Зарегистрировано Департаментом юстиции области Абай 15 декабря 2023 года № 191-18. Утратило силу решением маслихата района Аксуат области Абай от 25 декабря 2024 года № 24/11-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан в районе Аксуат
  kaz: Ақсуат ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-05
approved_by:
- '168004000002'
version_date:
  kaz: 2023-12-05
  rus: 2023-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/190274/kaz/05.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190274/rus/05.12.2023
