act_code: '195851'
requisite: Решение Урджарского районного маслихата области Абай от 10 апреля 2024 года № 14-251/VIII. Зарегистрировано Департаментом юстиции области Абай 19 апреля 2024 года № 264-18
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Урджарском районе
  kaz: Үржар ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-10
approved_by:
- '168010000002'
version_date:
  kaz: 2025-11-25
  rus: 2025-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/195851/kaz/25.11.2025
  rus: https://zan.gov.kz/client/#!/doc/195851/rus/25.11.2025
caused_by:
  code: '217465'
  requisite: Решение Урджарского районного маслихата области Абай от 25 ноября 2025 года № 25-590/VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 26 ноября 2025 года № 37473
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 10 апреля 2024 года № 14-251/VIII «Об определении размера и порядка оказания жилищной помощи в Урджарском районе»
    kaz: Үржар аудандық мәслихатының 2024 жылғы 10 сәуірдегі № 14-251/VIII «Үржар ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217465/rus
