act_code: '195851'
requisite: Решение Урджарского районного маслихата области Абай от 10 апреля 2024 года № 14-251/VIII. Зарегистрировано Департаментом юстиции области Абай 19 апреля 2024 года № 264-18
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Урджарском районе
  kaz: Үржар ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-10
approved_by:
- '168010000002'
version_date:
  kaz: 2024-04-10
  rus: 2024-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/195851/kaz/10.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195851/rus/10.04.2024
