act_code: '205569'
requisite: Решение маслихата района Мақаншы области Абай от 30 декабря 2024 года № 16-106/VIII. Утратило силу решением маслихата района Мақаншы области Абай от 30 декабря 2025 года № 32-232/VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Каратальского сельского округа района Мақаншы на 2025-2027 годы
  kaz: Мақаншы ауданы Қаратал ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168012000002'
version_date:
  kaz: 2025-12-05
  rus: 2025-12-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/205569/kaz/05.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205569/rus/05.12.2025
caused_by:
  code: '218177'
  requisite: Решение маслихата района Мақаншы области Абай от 5 декабря 2025 года № 29-208/VIII. Утратило силу решением маслихата района Мақаншы области Абай от 30 декабря 2025 года № 32-232/VIII (вводится в действие с 01.01.2026)
  title:
    rus: О внесении изменения в решение маслихата района Мақаншы от 30 декабря 2024 года № 16-106/VIII «О бюджете Каратальского сельского округа района Мақаншы на 2025-2027 годы»
    kaz: Мақаншы ауданы маслихатының 2024 жылғы 30 желтоқсандағы № 16-106/VIII «Мақаншы ауданы Қаратал ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/218177/rus
