act_code: '196079'
requisite: Решение Аягозского районного маслихата области Абай от 16 апреля 2024 года № 12/212-VIII. Зарегистрировано Департаментом юстиции области Абай 25 апреля 2024 года № 271-18
title:
  rus: Об утверждении размера и Правил оказания жилищной помощи в Аягозском районе
  kaz: Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен Қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-04-16
approved_by:
- '168006000002'
version_date:
  kaz: 2026-02-13
  rus: 2026-02-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/196079/kaz/13.02.2026
  rus: https://zan.gov.kz/client/#!/doc/196079/rus/13.02.2026
caused_by:
  code: '222207'
  requisite: Решение Аягозского районного маслихата области Абай от 13 февраля 2026 года № 32/587-VIII. Зарегистрировано в Министерстве юстиции Республики Казахстан 18 февраля 2026 года № 38000
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 16 апреля 2024 года № 12/212-VІІІ «Об определении размера и порядка оказания жилищной помощи в Аягозском районе»
    kaz: Аягөз аудандық мәслихатының 2024 жылғы 16 сәуірдегі № 12/212-VIIІ «Аягөз ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222207/rus
