act_code: '194901'
requisite: Решение Кокпектинского районного маслихата области Абай от 19 марта 2024 года № 11-3/4
title:
  rus: Об утверждении Регламента собрания местного сообщества по Кокпектинскому району
  kaz: Көкпекті ауданы бойынша жергілікті қоғамдастық жиналысының Регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-19
approved_by:
- '168011000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/194901/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194901/rus/19.03.2024
