act_code: '208999'
requisite: Решение маслихата района Аксуат области Абай от 31 марта 2025 года № 26/17-VIII. Зарегистрировано Департаментом юстиции области Абай 9 апреля 2025 года № 433-18
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в районе Аксуат
  kaz: Ақсуат ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2025-03-31
approved_by:
- '168004000002'
version_date:
  kaz: 2025-03-31
  rus: 2025-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/208999/kaz/31.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208999/rus/31.03.2025
