act_code: '192112'
requisite: Решение Урджарского районного маслихата области Абай от 26 декабря 2023 года № 9-213/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Каракольского сельского округа Урджарского района на 2024-2026 годы
  kaz: Үржар ауданы Қарақол ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '168010000002'
version_date:
  kaz: 2024-09-27
  rus: 2024-09-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/192112/kaz/27.09.2024
  rus: https://zan.gov.kz/client/#!/doc/192112/rus/27.09.2024
caused_by:
  code: '201097'
  requisite: Решение Урджарского районного маслихата области Абай от 27 сентября 2024 года № 18-346/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
  title:
    rus: О внесении изменения в решения Урджарского районного маслихата от 26 декабря 2023 года № 9-213/VIII «О бюджете Каракольского сельского округа Урджарского района на 2024-2026 годы»
    kaz: Үржар аудандық маслихатының 2023 жылғы 26 желтоқсандағы № 9-213/VIII «Үржар ауданы Қарақол ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201097/rus
