act_code: '205350'
requisite: Решение маслихата района Аксуат области Абай от 25 декабря 2024 года № 24/11-VIII. Зарегистрировано Департаментом юстиции области Абай 31 декабря 2024 года № 405-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан района Аксуат
  kaz: Ақсуат ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-12-25
approved_by:
- '168004000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205350/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205350/rus/25.12.2024
