act_code: '219514'
requisite: Решение Кокпектинского районного маслихата области Абай от 18 декабря 2025 года № 37-4/1
title:
  rus: Об утверждении плана по управлению пастбищами и их использованию по Кокпектинскому району на 2025-2029 годы
  kaz: Көкпекті ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2025-2029 жылдарға арналған жоспарын бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2025-12-18
approved_by:
- '168011000002'
version_date:
  kaz: 2025-12-18
  rus: 2025-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/219514/kaz/18.12.2025
  rus: https://zan.gov.kz/client/#!/doc/219514/rus/18.12.2025
