act_code: '195535'
requisite: Решение акима Айгызского сельского округа Аягозского района области Абай от 9 апреля 2024 года № 1
title:
  rus: Об установлении ограничительных мероприятий
  kaz: Шектеу іс-шараларын белгілеу туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-09
approved_by:
- '168006002002'
version_date:
  kaz: 2024-04-09
  rus: 2024-04-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/195535/kaz/09.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195535/rus/09.04.2024
