act_code: '216324'
requisite: Решение Бескарагайского районного маслихата области Абай от 23 октября 2025 года № 32/14-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по Бегенскому сельскому округу Бескарагайского района области Абай на 2026-2030 годы
  kaz: Абай облысы Бесқарағай ауданының Беген ауылдық округі бойынша жайылымдарды басқару және оларды пайдалану жөніндегі 2026-2030 жылдарға арналған жоспарды бекіту туралы
form: РЕШ
type_codes:
- ПЛАН
- РЕШ
approved_on: 2025-10-23
approved_by:
- '168007000002'
version_date:
  kaz: 2025-10-23
  rus: 2025-10-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/216324/kaz/23.10.2025
  rus: https://zan.gov.kz/client/#!/doc/216324/rus/23.10.2025
