act_code: '175451'
requisite: Решение маслихата области Абай от 14 декабря 2022 года № 11/71-VII. Утратило силу решением маслихата области Абай от 4 октября 2023 года № 8/58-VIIІ (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Правил регулирования миграционных процессов в области Абай
  kaz: Абай облысындағы көші-қон процестерін реттеу қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-14
approved_by:
- '168000000002'
version_date:
  kaz: 2022-12-14
  rus: 2022-12-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/175451/kaz/14.12.2022
  rus: https://zan.gov.kz/client/#!/doc/175451/rus/14.12.2022
