act_code: '205985'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2024 года № 23-8
title:
  rus: О бюджете Теректинского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Теректі ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2024-12-27
  rus: 2024-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205985/kaz/27.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205985/rus/27.12.2024
