act_code: '205985'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2024 года № 23-8
title:
  rus: О бюджете Теректинского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Теректі ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2025-12-02
  rus: 2025-12-02
source:
  kaz: https://zan.gov.kz/client/#!/doc/205985/kaz/02.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205985/rus/02.12.2025
caused_by:
  code: '217962'
  requisite: Решение Кокпектинского районного маслихата области Абай от 2 декабря 2025 года № 35-7
  title:
    rus: О внесении изменений в решение Кокпектинского районного маслихата от 27 декабря 2024 года № 23-8 «О бюджете Теректинского сельского округа на 2025-2027 годы»
    kaz: Көкпекті аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 23-8 «2025-2027 жылдарға арналған Теректі ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/217962/rus
