act_code: '202159'
requisite: Решение Бородулихинского районного маслихата области Абай от 24 октября 2024 года № 23-4-VIII. Зарегистрировано Департаментом юстиции области Абай 31 октября 2024 года № 361-18. Утратило силу решением Бородулихинского районного маслихата области Абай от 13 февраля 2026 года № 44-3-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Бородулихинскому району
  kaz: Бородулиха ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2024-10-24
approved_by:
- '16800800002'
version_date:
  kaz: 2024-10-24
  rus: 2024-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/202159/kaz/24.10.2024
  rus: https://zan.gov.kz/client/#!/doc/202159/rus/24.10.2024
