act_code: '202159'
requisite: Решение Бородулихинского районного маслихата области Абай от 24 октября 2024 года № 23-4-VIII. Зарегистрировано Департаментом юстиции области Абай 31 октября 2024 года № 361-18. Утратило силу решением Бородулихинского районного маслихата области Абай от 13 февраля 2026 года № 44-3-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Бородулихинскому району
  kaz: Бородулиха ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2024-10-24
approved_by:
- '16800800002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/202159/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/202159/rus/28.03.2025
caused_by:
  code: '208816'
  requisite: Решение Бородулихинского районного маслихата области Абай от 28 марта 2025 года № 31-8-VIII. Зарегистрировано Департаментом юстиции области Абай 3 апреля 2025 года № 432-18. Утратило силу решением Бородулихинского районного маслихата области Абай от 13 февраля 2026 года № 44-3-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении дополнения в решение Бородулихинского районного маслихата от 24 октября 2024 года № 23-4-VIII «Об определении размера и перечня категорий получателей жилищных сертификатов по Бородулихинскому району»
    kaz: Бородулиха аудандық мәслихатының 2024 жылғы 24 қазандағы № 23-4-VIII «Бородулиха ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» шешіміне толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/208816/rus
