act_code: '202872'
requisite: Решение маслихата района Мақаншы области Абай от 8 ноября 2024 года № 13-84/VIII. Зарегистрировано Департаментом юстиции области Абай 18 ноября 2024 года № 369-18
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах района Мақаншы
  kaz: Мақаншы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-11-08
approved_by:
- '168012000002'
version_date:
  kaz: 2025-05-22
  rus: 2025-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/202872/kaz/22.05.2025
  rus: https://zan.gov.kz/client/#!/doc/202872/rus/22.05.2025
caused_by:
  code: '210782'
  requisite: Решение маслихата района Мақаншы области Абай от 22 мая 2025 года № 21-139/VIII. Зарегистрировано Департаментом юстиции области Абай 27 мая 2025 года № 458-18
  title:
    rus: О внесении изменения в решение маслихата района Мақаншы от 8 ноября 2024 года № 13-84/VIIІ «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах района Мақаншы»
    kaz: Мақаншы ауданы мәслихатының 2024 жылғы 8 қарашадағы № 13-84/VIIІ «Мақаншы ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210782/rus
