act_code: '225557'
requisite: Решение акимата Жезкентского поселкового округа Бородулихинского района области Абай от 22 мая 2026 года № 5
title:
  rus: О переименовании улицы поселка Жезкент Жезкентского поселкового округа Бородулихинского района
  kaz: Бородулиха ауданы Жезкент кенттік округі Жезкент кентінің көшесін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-22
approved_by:
- '168008006001'
version_date:
  kaz: 2026-05-22
  rus: 2026-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/225557/kaz/22.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225557/rus/22.05.2026
