act_code: '175865'
requisite: Решение маслихата области Абай от 14 декабря 2022 года № 11/66-VII
title:
  rus: Об областном бюджете на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған облыстық бюджет туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-14
approved_by:
- '168000000002'
version_date:
  kaz: 2023-06-22
  rus: 2023-06-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/175865/kaz/22.06.2023
  rus: https://zan.gov.kz/client/#!/doc/175865/rus/22.06.2023
caused_by:
  code: '183218'
  requisite: Решение маслихата области Абай от 22 июня 2023 года № 4/30-VIIІ
  title:
    rus: О внесении изменений в решение маслихата области Абай от 14 декабря 2022 года № 11/66-VIІ «Об областном бюджете на 2023-2025 годы»
    kaz: Абай облысы мәслихатының 2022 жылғы 14 желтоқсандағы № 11/66-VІI «2023-2025 жылдарға арналған облыстық бюджет туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/183218/rus
