act_code: '195849'
requisite: Решение Кокпектинского районного маслихата области Абай от 10 апреля 2024 года № 12-5/2. Зарегистрировано Департаментом юстиции области Абай 19 апреля 2024 года № 263-18
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования, норм их предельной заполняемости, требований к их материально-техническому и организационному обеспечению, границ прилегающих территорий, в которых запрещено проведение пикетирования по Кокпектинскому району
  kaz: Көкпекті ауданы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, оларды пайдалану тәртібін, олардың шекті толу нормаларын, оларды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-04-10
approved_by:
- '168011000002'
version_date:
  kaz: 2024-04-10
  rus: 2024-04-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/195849/kaz/10.04.2024
  rus: https://zan.gov.kz/client/#!/doc/195849/rus/10.04.2024
