act_code: '179652'
requisite: Решение Урджарского районного маслихата области Абай от 11 апреля 2023 года № 1-14/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 30 марта 2026 года № 33-672/VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» аппарата Урджарского районного маслихата
  kaz: Үржар аудандық мәслихаты аппаратының «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың Әдістемесін бекіту туралы
form: РЕШ
type_codes:
- МЕТ
- РЕШ
approved_on: 2023-04-11
approved_by:
- '168010000002'
version_date:
  kaz: 2023-04-11
  rus: 2023-04-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/179652/kaz/11.04.2023
  rus: https://zan.gov.kz/client/#!/doc/179652/rus/11.04.2023
