act_code: '186293'
requisite: Решение Урджарского районного маслихата области Абай от 20 сентября 2023 года № 5-107/VIII
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества на территории Урджарского района
  kaz: Үржар ауданының аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-09-20
approved_by:
- '168010000002'
version_date:
  kaz: 2023-09-20
  rus: 2023-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/186293/kaz/20.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186293/rus/20.09.2023
