act_code: '211890'
requisite: Решение маслихата города Семей области Абай от 27 июня 2025 года № 45/242-VIII
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год по городу Семей
  kaz: Семей қаласы бойынша 2025 жылға арналған шетелдіктер үшін туристік жарнаның мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-06-27
approved_by:
- '168002000002'
version_date:
  kaz: 2025-06-27
  rus: 2025-06-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/211890/kaz/27.06.2025
  rus: https://zan.gov.kz/client/#!/doc/211890/rus/27.06.2025
