act_code: '174115'
requisite: Решение маслихата области Абай от 18 ноября 2022 года № 10/58-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 ноября 2022 года № 30658
title:
  rus: Об утверждении Правил присвоения звания «Почетный гражданин области Абай (города, района)»
  kaz: «Абай облысының (қаласының, ауданының) Құрметті азаматы» атағын беру қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-18
approved_by:
- '168000000002'
version_date:
  kaz: 2022-11-18
  rus: 2022-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/174115/kaz/18.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174115/rus/18.11.2022
