act_code: '205981'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2024 года № 23-5
title:
  rus: О бюджете Кокжайыкского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Көкжайық ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2025-02-28
  rus: 2025-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205981/kaz/28.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205981/rus/28.02.2025
caused_by:
  code: '207844'
  requisite: Решение Кокпектинского районного маслихата области Абай от 28 февраля 2025 года № 25-4
  title:
    rus: О внесении изменений в решение Кокпектинского районного маслихата от 27 декабря 2024 года № 23-5 «О бюджете Кокжайыкского сельского округа на 2025-2027 годы»
    kaz: Көкпекті аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 23-5 «2025-2027 жылдарға арналған Көкжайық ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207844/rus
