act_code: '192025'
requisite: Решение Урджарского районного маслихата области Абай от 26 декабря 2023 года № 9-202/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Ельтайского сельского округа Урджарского района на 2024-2026 годы
  kaz: Үржар ауданы Елтай ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '168010000002'
version_date:
  kaz: 2024-11-28
  rus: 2024-11-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/192025/kaz/28.11.2024
  rus: https://zan.gov.kz/client/#!/doc/192025/rus/28.11.2024
caused_by:
  code: '203349'
  requisite: Решение Урджарского районного маслихата области Абай от 28 ноября 2024 года № 20-392/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
  title:
    rus: О внесении изменения в решение Урджарского районного маслихата от 26 декабря 2023 года № 9-202/VIII «О бюджете Ельтайского сельского округа Урджарского района на 2024-2026 годы»
    kaz: Үржар аудандық маслихатының 2023 жылғы 26 желтоқсандағы № 9-202/VIII «Үржар ауданы Елтай ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/203349/rus
