act_code: '184223'
requisite: Решение Кокпектинского районного маслихата области Абай от 12 июля 2023 года № 4-5/5. Зарегистрировано Департаментом юстиции области Абай 24 июля 2023 года № 103-18. Утратило силу решением Кокпектинского районного маслихата области Абай от 15 октября 2025 года № 32-5/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Кокпектинскому району
  kaz: Көкпекті ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-07-12
approved_by:
- '168011000002'
version_date:
  kaz: 2023-12-06
  rus: 2023-12-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/184223/kaz/06.12.2023
  rus: https://zan.gov.kz/client/#!/doc/184223/rus/06.12.2023
caused_by:
  code: '190270'
  requisite: Решение Кокпектинского районного маслихата области Абай от 6 декабря 2023 года № 8-4/2. Зарегистрировано Департаментом юстиции области Абай 14 декабря 2023 года № 189-18. Утратило силу решением Кокпектинского районного маслихата области Абай от 15 октября 2025 года № 32-5/4 (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Кокпектинского районного маслихата от 12 июля 2023 года № 4-5/5 «Об определении размера и перечня категорий получателей жилищных сертификатов по Кокпектинскому району»
    kaz: Көкпекті аудандық мәслихатының 2023 жылғы 12 шілдедегі № 4-5/5 «Көкпекті ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190270/rus
