act_code: '177909'
requisite: Решение Аягозского районного маслихата области Абай от 27 декабря 2022 года № 20/406-VII
title:
  rus: О бюджете Баршатасского сельского округа Аягозского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Аягөз ауданының Баршатас ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '168006000002'
version_date:
  kaz: 2023-11-01
  rus: 2023-11-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/177909/kaz/01.11.2023
  rus: https://zan.gov.kz/client/#!/doc/177909/rus/01.11.2023
caused_by:
  code: '187991'
  requisite: Решение Аягозского районного маслихата области Абай от 1 ноября 2023 года № 8/118-VIII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 27 декабря 2022 года № 20/406-VIІ «О бюджете Баршатасского сельского округа Аягозского района на 2023-2025 годы»
    kaz: «2023-2025 жылдарға арналған Аягөз ауданының Баршатас ауылдық округінің бюджеті туралы» Аягөз аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 20/406-VІI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/187991/rus
