act_code: '202261'
requisite: Решение Аягозского районного маслихата области Абай от 31 октября 2024 года № 17/302-VIII
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по Аягозскому району
  kaz: Аягөз ауданы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-31
approved_by:
- '168006000002'
version_date:
  kaz: 2024-10-31
  rus: 2024-10-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/202261/kaz/31.10.2024
  rus: https://zan.gov.kz/client/#!/doc/202261/rus/31.10.2024
