act_code: '186425'
requisite: Решение Урджарского районного маслихата области Абай от 20 сентября 2023 года № 5-113/VIII. Зарегистрировано Департаментом юстиции области Абай 22 сентября 2023 года № 124-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-09-20
approved_by:
- '168010000002'
version_date:
  kaz: 2023-09-20
  rus: 2023-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/186425/kaz/20.09.2023
  rus: https://zan.gov.kz/client/#!/doc/186425/rus/20.09.2023
