act_code: '186425'
requisite: Решение Урджарского районного маслихата области Абай от 20 сентября 2023 года № 5-113/VIII. Зарегистрировано Департаментом юстиции области Абай 22 сентября 2023 года № 124-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-09-20
approved_by:
- '168010000002'
version_date:
  kaz: 2023-12-01
  rus: 2023-12-01
source:
  kaz: https://zan.gov.kz/client/#!/doc/186425/kaz/01.12.2023
  rus: https://zan.gov.kz/client/#!/doc/186425/rus/01.12.2023
caused_by:
  code: '189626'
  requisite: Решение Урджарского районного маслихата области Абай от 1 декабря 2023 года № 7-177/VIII. Зарегистрировано Департаментом юстиции области Абай 6 декабря 2023 года № 179-18
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата от 20 сентября 2023 года № 5-113/VIII «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
    kaz: Үржар аудандық мәслихатының 2023 жылғы 20 қыркүйектегі № 5-113/VIII «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/189626/rus
