act_code: '177654'
requisite: Решение маслихата Бородулихинского района области Абай от 30 декабря 2022 года № 26-16-VII
title:
  rus: О бюджете Петропавловского сельского округа Бородулихинского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Бородулиха ауданы Петропавловка ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '16800800002'
version_date:
  kaz: 2023-12-08
  rus: 2023-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/177654/kaz/08.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177654/rus/08.12.2023
caused_by:
  code: '190042'
  requisite: Решение Бородулихинского районного маслихата области Абай от 8 декабря 2023 года № 12-9-VIII
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 30 декабря 2022 года № 26-16-VII «О бюджете Петропавловского сельского округа Бородулихинского района на 2023-2025 годы»
    kaz: Бородулиха аудандық мәслихатының 2022 жылғы 30 желтоқсандағы № 26-16-VII «2023-2025 жылдарға арналған Бородулиха ауданы Петропавловка ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190042/rus
