act_code: '191707'
requisite: Решение Урджарского районного маслихата области Абай от 22 декабря 2023 года № 8-185/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Урджарского района на 2024-2026 годы
  kaz: Үржар ауданының 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '168010000002'
version_date:
  kaz: 2024-09-20
  rus: 2024-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/191707/kaz/20.09.2024
  rus: https://zan.gov.kz/client/#!/doc/191707/rus/20.09.2024
caused_by:
  code: '201237'
  requisite: Решение Урджарского районного маслихата области Абай от 20 сентября 2024 года № 18-339/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
  title:
    rus: О внесении изменений в решение Урджарского районного маслихата «О бюджете Урджарского района на 2024-2026 годы» от 22 декабря 2023 года № 8-185/VIII
    kaz: «Үржар аудандық мәслихатының 2023 жылғы 22 желтоқсандағы № 8-185/VIII «Үржар ауданының 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/201237/rus
