act_code: '194955'
requisite: Решение Кокпектинского районного маслихата области Абай от 19 марта 2024 года № 11-2. Зарегистрировано Департаментом юстиции области Абай 29 марта 2024 года № 240-18. Утратило силу решением Кокпектинского районного маслихата области Абай от 27 апреля 2026 года № 43-11/1 (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Кокпектинском районе
  kaz: Көкпекті ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-19
approved_by:
- '168011000002'
version_date:
  kaz: 2024-03-19
  rus: 2024-03-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/194955/kaz/19.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194955/rus/19.03.2024
