act_code: '206427'
requisite: Решение Абайского районного маслихата области Абай от 31 декабря 2024 года № 24/3-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/3-VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Кенгирбай бийского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Кеңгірбай би ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '168005000002'
version_date:
  kaz: 2025-10-17
  rus: 2025-10-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/206427/kaz/17.10.2025
  rus: https://zan.gov.kz/client/#!/doc/206427/rus/17.10.2025
caused_by:
  code: '215732'
  requisite: Решение Абайского районного маслихата области Абай от 17 октября 2025 года № 32/3-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/3-VIII (вводится в действие с 01.01.2026)
  title:
    rus: О внесении изменений в решение маслихата от 31 декабря 2024 года № 24/3-VIII «О бюджете Кенгирбай бийского сельского округа на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 31 желтоқсандағы № 24/3-VIII «2025-2027 жылдарға арналған Кеңгірбай би ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215732/rus
