act_code: '205866'
requisite: Решение Жарминского районного маслихата области Абай от 5 января 2025 года № 20/384-VIII
title:
  rus: О бюджете поселка Жангизтобе Жарминского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Жарма ауданы Жаңғызтөбе кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-05
approved_by:
- '168009000002'
version_date:
  kaz: 2025-09-05
  rus: 2025-09-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/205866/kaz/05.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205866/rus/05.09.2025
caused_by:
  code: '213925'
  requisite: Решение Жарминского районного маслихата области Абай от 5 сентября 2025 года № 28/476-VIII
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 05 января 2025 года № 20/384-VІII «О бюджете поселка Жангизтобе Жарминского района на 2025-2027 годы»
    kaz: Жарма аудандық мәслихатының 2025 жылғы 05 қаңтардағы № 20/384-VIІI «2025-2027 жылдарға арналған Жарма ауданы Жаңғызтөбе кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/213925/rus
