act_code: '189570'
requisite: Решение Курчатовского городского маслихата области Абай от 30 ноября 2023 года № 12/72-VIII. Зарегистрировано Департаментом юстиции области Абай 5 декабря 2023 года № 174-18. Утратило силу решением Курчатовского городского маслихата области Абай от 30 апреля 2024 года № 17/108-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в городе Курчатов
  kaz: Курчатов қаласында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-30
approved_by:
- '168003000002'
version_date:
  kaz: 2023-11-30
  rus: 2023-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/189570/kaz/30.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189570/rus/30.11.2023
