act_code: '205960'
requisite: Решение Бескарагайского районного маслихата области Абай от 30 декабря 2024 года № 26/11-VIII
title:
  rus: О бюджете Ерназаровского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Ерназар ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168007000002'
version_date:
  kaz: 2025-07-10
  rus: 2025-07-10
source:
  kaz: https://zan.gov.kz/client/#!/doc/205960/kaz/10.07.2025
  rus: https://zan.gov.kz/client/#!/doc/205960/rus/10.07.2025
caused_by:
  code: '212403'
  requisite: Решение Бескарагайского районного маслихата области Абай от 10 июля 2025 года № 29/11-VIII
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 30 декабря 2024 года № 26/11-VIII «О бюджете Ерназаровского сельского округа на 2025-2027 годы»
    kaz: Бесқарағай аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 26/11-VIII «2025-2027 жылдарға арналған Ерназар ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212403/rus
