act_code: '177220'
requisite: Решение Абайского районного маслихата области Абай от 30 декабря 2022 года № 31/8-VII. Утратило силу решением Абайского районного маслихата области Абай от 28 декабря 2023 года № 12/8-VIII (вводится в действие с 01.01.2024)
title:
  rus: О бюджете Медеуского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Медеу ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '168005000002'
version_date:
  kaz: 2023-10-24
  rus: 2023-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/177220/kaz/24.10.2023
  rus: https://zan.gov.kz/client/#!/doc/177220/rus/24.10.2023
caused_by:
  code: '187603'
  requisite: Решение Абайского районного маслихата области Абай от 24 октября 2023 года № 9/8-VIII. Утратило силу решением Абайского районного маслихата области Абай от 28 декабря 2023 года № 12/8-VIII (вводится в действие с 01.01.2024)
  title:
    rus: О внесении изменений в решение маслихата от 30 декабря 2022 года № 31/8-VII «О бюджете Медеуского сельского округа на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 30 желтоқсандағы № 31/8-VII «2023-2025 жылдарға арналған Медеу ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы»
  link: https://zan.gov.kz/client/#!/doc/187603/rus
