act_code: '208598'
requisite: Решение Абайского районного маслихата области Абай от 28 марта 2025 года № 25/6-VIII
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества в Абайском районе
  kaz: Абай ауданында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-03-28
approved_by:
- '168005000002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/208598/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208598/rus/28.03.2025
