act_code: '187979'
requisite: Решение Курчатовского городского маслихата области Абай от 24 октября 2023 года № 11/68-VIII. Зарегистрировано Департаментом юстиции области Абай 6 ноября 2023 года № 141-18
title:
  rus: Об утверждении минимального размера расходов на управление объектом кондоминиума и содержание общего имущества объекта кондоминиума города Курчатов на 2023 год
  kaz: 2023 жылға Курчатов қаласының кондоминиум объектісін басқаруға және кондоминиум объектісінің ортақ мүлкін күтіп-ұстауға арналған шығыстардың ең төмен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-24
approved_by:
- '168003000002'
version_date:
  kaz: 2023-10-24
  rus: 2023-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/187979/kaz/24.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187979/rus/24.10.2023
