act_code: '189564'
requisite: Решение Жарминского районного маслихата области Абай от 30 ноября 2023 года № 9/154-VIII. Зарегистрировано Департаментом юстиции области Абай 5 декабря 2023 года № 173-18
title:
  rus: О ставках земельного налога по Жарминскому району
  kaz: Жарма ауданы бойынша жер салығының мөлшерлемелері туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-30
approved_by:
- '168009000002'
version_date:
  kaz: 2023-11-30
  rus: 2023-11-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/189564/kaz/30.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189564/rus/30.11.2023
