act_code: '177669'
requisite: Решение маслихата Бородулихинского района области Абай от 30 декабря 2022 года № 26-11-VII
title:
  rus: О бюджете Кунарлинского сельского округа Бородулихинского района на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Бородулиха ауданы Құнарлы ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '168008000002'
version_date:
  kaz: 2022-12-30
  rus: 2022-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/177669/kaz/30.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177669/rus/30.12.2022
