act_code: '177229'
requisite: Решение Абайского районного маслихата области Абай от 30 декабря 2022 года № 31/10-VII. Утратило силу решением Абайского районного маслихата области Абай от 28 декабря 2023 года № 12/10-VIII (вводится в действие с 01.01.2024)
title:
  rus: О бюджете Токтамысского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Тоқтамыс ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-30
approved_by:
- '168005000002'
version_date:
  kaz: 2023-08-22
  rus: 2023-08-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/177229/kaz/22.08.2023
  rus: https://zan.gov.kz/client/#!/doc/177229/rus/22.08.2023
caused_by:
  code: '185322'
  requisite: Решение Абайского районного маслихата области Абай от 22 августа 2023 года № 6/10-VIII. Утратило силу решением Абайского районного маслихата области Абай от 28 декабря 2023 года № 12/10-VIII (вводится в действие с 01.01.2024)
  title:
    rus: О внесении изменений в решение маслихата от 30 декабря 2022 года № 31/10-VIІ «О бюджете Токтамысского сельского округа на 2023-2025 годы»
    kaz: Мәслихаттың 2022 жылғы 30 желтоқсандағы № 31/10-VIІ «2023-2025 жылдарға арналған Тоқтамыс ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/185322/rus
