act_code: '203204'
requisite: Решение маслихата города Семей области Абай от 20 ноября 2024 года № 34/182-VIII
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по городу Семей
  kaz: Семей қаласы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-20
approved_by:
- '168002000002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/203204/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203204/rus/20.11.2024
