act_code: '204904'
requisite: Решение Абайского районного маслихата области Абай от 23 декабря 2024 года № 23/3-VIII. Утратило силу решением Абайского районного маслихата области Абай от 18 декабря 2025 года № 35/5-VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Абайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Абай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '168005000002'
version_date:
  kaz: 2024-12-23
  rus: 2024-12-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/204904/kaz/23.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204904/rus/23.12.2024
