act_code: '204904'
requisite: Решение Абайского районного маслихата области Абай от 23 декабря 2024 года № 23/3-VIII. Утратило силу решением Абайского районного маслихата области Абай от 18 декабря 2025 года № 35/5-VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Абайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Абай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-23
approved_by:
- '168005000002'
version_date:
  kaz: 2025-10-07
  rus: 2025-10-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/204904/kaz/07.10.2025
  rus: https://zan.gov.kz/client/#!/doc/204904/rus/07.10.2025
caused_by:
  code: '215394'
  requisite: Решение Абайского районного маслихата области Абай от 7 октября 2025 года № 31/13-VIII. Утратило силу решением Абайского районного маслихата области Абай от 18 декабря 2025 года № 35/5-VIII (вводится в действие с 01.01.2026)
  title:
    rus: О внесении изменений в решение маслихата от 23 декабря 2024 года № 23/3-VІІІ «О бюджете Абайского района на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 23 желтоқсандағы № 23/3-VІІІ «2025-2027 жылдарға арналған Абай ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/215394/rus
