act_code: '188657'
requisite: Решение маслихата города Семей области Абай от 17 ноября 2023 года № 13/77-VIII. Зарегистрировано Департаментом юстиции области Абай 21 ноября 2023 года № 156-18. Утратило силу решением маслихата города Семей области Абай от 20 ноября 2024 года № 34/177-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении ставок туристского взноса для иностранцев либо физических или юридических лиц, оплачивающих проживание иностранца (приглашающая сторона, туроператор) по городу Семей
  kaz: Семей қаласы бойынша шетелдіктер немесе шетелдіктің тұруына ақы төлейтін жеке немесе заңды тұлғалар (шақырушы тарап, туроператор) үшін туристік жарнаның мөлшерлемелерiн бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-11-17
approved_by:
- '168002000002'
version_date:
  kaz: 2023-11-17
  rus: 2023-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/188657/kaz/17.11.2023
  rus: https://zan.gov.kz/client/#!/doc/188657/rus/17.11.2023
