act_code: '174113'
requisite: Решение маслихата области Абай от 18 ноября 2022 года № 10/57-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 22 ноября 2022 года № 30661
title:
  rus: Об утверждении Положения о награждении Почетной грамотой области Абай
  kaz: Абай облысының Құрмет грамотасымен наградтау туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-18
approved_by:
- '168000000002'
version_date:
  kaz: 2022-11-18
  rus: 2022-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/174113/kaz/18.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174113/rus/18.11.2022
