act_code: '205586'
requisite: Решение маслихата района Мақаншы области Абай от 30 декабря 2024 года № 16-104/VIII. Утратило силу решением маслихата района Мақаншы области Абай от 30 декабря 2025 года № 32-232/VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Карабутинского сельского округа района Мақаншы на 2025-2027 годы
  kaz: Мақаншы ауданы Қарабұта ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168012000002'
version_date:
  kaz: 2024-12-30
  rus: 2024-12-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/205586/kaz/30.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205586/rus/30.12.2024
