act_code: '203200'
requisite: Решение маслихата города Семей области Абай от 20 ноября 2024 года № 34/181-VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по городу Семей
  kaz: Семей қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-20
approved_by:
- '168002000002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/203200/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203200/rus/20.11.2024
