act_code: '206412'
requisite: Решение Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-401/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 26 декабря 2025 года № 31-650/VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Урджарского района на 2025-2027 годы
  kaz: Үржар ауданының 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-24
approved_by:
- '168010000002'
version_date:
  kaz: 2024-12-24
  rus: 2024-12-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206412/kaz/24.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206412/rus/24.12.2024
