act_code: '192941'
requisite: Решение Урджарского районного маслихата области Абай от 20 января 2024 года № 11-230/VIII. Зарегистрировано Департаментом юстиции области Абай 26 января 2024 года № 217-18
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования, нормы их предельной заполняемости, требований к их материально-техническому и организационному обеспечению, границ прилегающих территорий, в которых запрещено проведение пикетирования в Урджарском районе
  kaz: Үржар ауданында бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, оларды пайдалану тәртібін, олардың шекті толу нормаларын, оларды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған  іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-20
approved_by:
- '168010000002'
version_date:
  kaz: 2024-01-20
  rus: 2024-01-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/192941/kaz/20.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192941/rus/20.01.2024
