act_code: '222377'
requisite: Решение Абайского районного маслихата области Абай от 18 февраля 2026 года № 37/5-VIII
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Абайскому району
  kaz: Абай ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2026-02-18
approved_by:
- '168005000002'
version_date:
  kaz: 2026-02-18
  rus: 2026-02-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/222377/kaz/18.02.2026
  rus: https://zan.gov.kz/client/#!/doc/222377/rus/18.02.2026
