act_code: '181295'
requisite: Решение акима Бородулихинского района области Абай от 12 мая 2023 года № 4. Отменено решением акима Бородулихинского района области Абай от 7 августа 2023 года № 7 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера местного масштаба в селе Андроновка Переменовского сельского округа Бородулихинского района области Абай
  kaz: Абай облысы Бородулиха ауданы Переменовка ауылдық округінің Андроновка ауылында жергілікті ауқымдағы техногендік сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-12
approved_by:
- '168008000003'
version_date:
  kaz: 2023-05-12
  rus: 2023-05-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/181295/kaz/12.05.2023
  rus: https://zan.gov.kz/client/#!/doc/181295/rus/12.05.2023
