act_code: '201380'
requisite: Решение Аягозского районного маслихата области Абай от 20 сентября 2024 года № 15/290-VIII. Зарегистрировано Департаментом юстиции области Абай 4 октября 2024 года № 349-18. Утратило силу решением Аягозского районного маслихата области Абай от 15 октября 2025 года № 29/494-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Аягозскому району
  kaz: Аягөз ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2024-09-20
approved_by:
- '168006000002'
version_date:
  kaz: 2025-03-31
  rus: 2025-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/201380/kaz/31.03.2025
  rus: https://zan.gov.kz/client/#!/doc/201380/rus/31.03.2025
caused_by:
  code: '209116'
  requisite: Решение Аягозского районного маслихата области Абай от 31 марта 2025 года № 23/424-VIII. Зарегистрировано Департаментом юстиции области Абай 14 апреля 2025 года № 437-18. Утратило силу решением Аягозского районного маслихата области Абай от 15 октября 2025 года № 29/494-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 20 сентября 2024 года № 15/290-VІІІ «Об определении размера и перечня категорий получателей жилищных сертификатов по Аягозскому району»
    kaz: Аягөз аудандық мәслихатының 2024 жылғы 20 қыркүйектегі № 15/290-VIII «Аягөз ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209116/rus
