act_code: '201380'
requisite: Решение Аягозского районного маслихата области Абай от 20 сентября 2024 года № 15/290-VIII. Зарегистрировано Департаментом юстиции области Абай 4 октября 2024 года № 349-18. Утратило силу решением Аягозского районного маслихата области Абай от 15 октября 2025 года № 29/494-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Аягозскому району
  kaz: Аягөз ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- ПРЧ
- РЕШ
approved_on: 2024-09-20
approved_by:
- '168006000002'
version_date:
  kaz: 2024-09-20
  rus: 2024-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/201380/kaz/20.09.2024
  rus: https://zan.gov.kz/client/#!/doc/201380/rus/20.09.2024
