act_code: '205778'
requisite: Решение Урджарского районного маслихата области Абай от 27 декабря 2024 года № 21-426/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 26 декабря 2025 года № 31-650/VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Урджарского сельского округа Урджарского района на 2025-2027 годы
  kaz: Үржар ауданы Үржар ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168010000002'
version_date:
  kaz: 2025-10-24
  rus: 2025-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/205778/kaz/24.10.2025
  rus: https://zan.gov.kz/client/#!/doc/205778/rus/24.10.2025
caused_by:
  code: '216065'
  requisite: Решение Урджарского районного маслихата области Абай от 24 октября 2025 года № 28-567/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 26 декабря 2025 года № 31-650/VIII (вводится в действие с 01.01.2026)
  title:
    rus: О внесении изменения в решение Урджарского районного маслихата от 27 декабря 2024 года № 21-426/VIIІ «О бюджете Урджарского сельского округа Урджарского района на 2025-2027 годы»
    kaz: Үржар аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 21-426/VIII «Үржар ауданы Үржар ауылдық округінің 2025-2027 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/216065/rus
