act_code: '204645'
requisite: Решение Курчатовского городского маслихата области Абай от 18 декабря 2024 года № 24/148-VIII
title:
  rus: Об утверждении программы по управлению коммунальными отходами по городу Курчатов на 2025-2029 годы
  kaz: Курчатов қаласының коммуналдық қалдықтарды басқарудың 2025-2029 жылдарға арналған бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2024-12-18
approved_by:
- '168003000002'
version_date:
  kaz: 2024-12-18
  rus: 2024-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/204645/kaz/18.12.2024
  rus: https://zan.gov.kz/client/#!/doc/204645/rus/18.12.2024
