act_code: '214477'
requisite: Решение Урджарского районного маслихата области Абай от 19 сентября 2025 года № 27-532/VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Урджарскому району
  kaz: Үржар ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2025-09-19
approved_by:
- '168010000002'
version_date:
  kaz: 2025-09-19
  rus: 2025-09-19
source:
  kaz: https://zan.gov.kz/client/#!/doc/214477/kaz/19.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214477/rus/19.09.2025
