act_code: '172954'
requisite: Решение маслихата области Абай от 5 октября 2022 года № 8/43-VII
title:
  rus: Об утверждении Правил выпаса сельскохозяйственных животных по области Абай
  kaz: Абай облысы бойынша ауыл шаруашылығы жануарларын жаю қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-10-05
approved_by:
- '168000000002'
version_date:
  kaz: 2022-10-05
  rus: 2022-10-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/172954/kaz/05.10.2022
  rus: https://zan.gov.kz/client/#!/doc/172954/rus/05.10.2022
