act_code: '206223'
requisite: Решение маслихата района Аксуат области Абай от 25 декабря 2024 года № 24/7-VIII
title:
  rus: Об утверждении тарифов для населения на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по района Аксуат
  kaz: Ақсуат ауданы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '168004000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/206223/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206223/rus/25.12.2024
