act_code: '192106'
requisite: Решение Урджарского районного маслихата области Абай от 26 декабря 2023 года № 9-210/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Кабанбайского сельского округа Урджарского района на 2024-2026 годы
  kaz: Үржар ауданы Қабанбай ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '168010000002'
version_date:
  kaz: 2023-12-26
  rus: 2023-12-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/192106/kaz/26.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192106/rus/26.12.2023
