act_code: '177199'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2022 года № 28-5/1
title:
  rus: О бюджете Бигашского сельского округа на 2023-2025 годы
  kaz: 2023-2025 жылдарға арналған Биғаш ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2023-12-11
  rus: 2023-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/177199/kaz/11.12.2023
  rus: https://zan.gov.kz/client/#!/doc/177199/rus/11.12.2023
caused_by:
  code: '190495'
  requisite: Решение Кокпектинского районного маслихата области Абай от 11 декабря 2023 года № 9-2
  title:
    rus: О внесении изменений в решение Кокпектинского районного маслихата от 27 декабря 2022 года № 28-5/1 «О бюджете Бигашского сельского округа на 2023-2025 годы»
    kaz: Көкпекті аудандық мәслихатының 2022 жылғы 27 желтоқсандағы № 28-5/1 «2023-2025 жылдарға арналған Биғаш ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/190495/rus
