act_code: '225780'
requisite: Решение акима Аягозского района области Абай от 29 мая 2026 года № 1
title:
  rus: Об объявлении чрезвычайной ситуации природного характера местного масштаба в Аягозском районе области Абай
  kaz: Аягөз ауданының аумағында жергілікті ауқымдағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-29
approved_by:
- '168006000003'
version_date:
  kaz: 2026-05-29
  rus: 2026-05-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/225780/kaz/29.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225780/rus/29.05.2026
