act_code: '203613'
requisite: Решение Жарминского районного маслихата области Абай от 27 ноября 2024 года № 19/346-VIII. Зарегистрировано Департаментом юстиции области Абай 4 декабря 2024 года № 383-18
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Жарминском районе
  kaz: Жарма ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-27
approved_by:
- '168009000002'
version_date:
  kaz: 2024-11-27
  rus: 2024-11-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/203613/kaz/27.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203613/rus/27.11.2024
