act_code: '183616'
requisite: Решение маслихата города Семей области Абай от 23 июня 2023 года № 5/40-VIII
title:
  rus: Об утверждении «Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат маслихата города Семей области Абай»
  kaz: «Абай облысы Семей қаласы мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттік әкімшілік қызметшілерінің қызметін бағалаудың әдістемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-23
approved_by:
- '168002000002'
version_date:
  kaz: 2023-06-23
  rus: 2023-06-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/183616/kaz/23.06.2023
  rus: https://zan.gov.kz/client/#!/doc/183616/rus/23.06.2023
