act_code: '199335'
requisite: Решение маслихата района Мақаншы области Абай от 26 июля 2024 года № 8-48/VIII. Утратило силу решением маслихата района Мақаншы области Абай от 30 декабря 2024 года № 16-112/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Карабулакского сельского округа района Мақаншы на 2024-2026 годы
  kaz: Мақаншы ауданы Қарабұлақ ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-26
approved_by:
- '168012000002'
version_date:
  kaz: 2024-07-26
  rus: 2024-07-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/199335/kaz/26.07.2024
  rus: https://zan.gov.kz/client/#!/doc/199335/rus/26.07.2024
