act_code: '194346'
requisite: Решение Жарминского районного маслихата области Абай от 4 марта 2024 года № 11/210-VIII. Зарегистрировано Департаментом юстиции области Абай 13 марта 2024 года № 235-18
title:
  rus: Об определении специализированных мест для организации и проведения мирных собраний, порядка их использования, норм их предельной заполняемости, требований к их материально-техническому и организационному обеспечению, границ прилегающих территорий, в которых запрещено проведение пикетирования по Жарминскому району
  kaz: Жарма ауданы бойынша бейбіт жиналыстарды ұйымдастыру және өткізу үшін арнайы орындарды, оларды пайдалану тәртібін, олардың шекті толу нормаларын, оларды материалдық-техникалық және ұйымдастырушылық қамтамасыз етуге қойылатын талаптарды, пикеттеуді өткізуге тыйым салынған іргелес аумақтардың шекараларын айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-04
approved_by:
- '168009000002'
version_date:
  kaz: 2024-03-04
  rus: 2024-03-04
source:
  kaz: https://zan.gov.kz/client/#!/doc/194346/kaz/04.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194346/rus/04.03.2024
