act_code: '225206'
requisite: Решение акима Екпинского сельского округа района Аксуат области Абай от 13 мая 2026 года № 16
title:
  rus: О присвоении наименований Улицам «Квартал» села Аккала
  kaz: Аққала ауылының «Квартал» көшелеріне атау беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-05-13
approved_by:
- '168004002002'
version_date:
  kaz: 2026-05-13
  rus: 2026-05-13
source:
  kaz: https://zan.gov.kz/client/#!/doc/225206/kaz/13.05.2026
  rus: https://zan.gov.kz/client/#!/doc/225206/rus/13.05.2026
