act_code: '203624'
requisite: Решение маслихата города Семей области Абай от 20 ноября 2024 года № 34/179-VIII. Зарегистрировано Департаментом юстиции области Абай 25 ноября 2024 года № 376-18
title:
  rus: О признании утратившим силу решения маслихата города Семей Восточно-Казахстанской области от 31 декабря 2021 года № 21/154-VII «Об утверждении норм образования и накопления коммунальных отходов по городу Семей»
  kaz: Шығыс Қазақстан облысы Семей қаласы мәслихатының 2021 жылғы 31 желтоқсандағы № 21/154-VII «Семей қаласы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-20
approved_by:
- '168002000002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/203624/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203624/rus/20.11.2024
