act_code: '205992'
requisite: Решение Кокпектинского районного маслихата области Абай от 27 декабря 2024 года № 23-3
title:
  rus: О бюджете Бигашского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Биғаш ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-27
approved_by:
- '168011000002'
version_date:
  kaz: 2025-02-28
  rus: 2025-02-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/205992/kaz/28.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205992/rus/28.02.2025
caused_by:
  code: '207841'
  requisite: Решение Кокпектинского районного маслихата области Абай от 28 февраля 2025 года № 25-2
  title:
    rus: О внесении изменений и дополнений в решение Кокпектинского районного маслихата от 27 декабря 2024 года № 23-3 «О бюджете Бигашского сельского округа на 2025-2027 годы»
    kaz: Көкпекті аудандық мәслихатының 2024 жылғы 27 желтоқсандағы № 23-3 «2025-2027 жылдарға арналған Биғаш ауылдық округінің бюджеті туралы» шешіміне өзгерістер мен толықтырулар енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207841/rus
