act_code: '205784'
requisite: Решение маслихата города Семей области Абай от 25 декабря 2024 года № 38/200-VIII
title:
  rus: Об утверждении Программы управления коммунальными отходами города Семей на 2024-2028 годы
  kaz: Семей қаласының 2024-2028 жылдарға арналған коммуналдық қалдықтарын басқару жөніндегі бағдарламасын бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2024-12-25
approved_by:
- '168002000002'
version_date:
  kaz: 2024-12-25
  rus: 2024-12-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/205784/kaz/25.12.2024
  rus: https://zan.gov.kz/client/#!/doc/205784/rus/25.12.2024
