act_code: '203619'
requisite: Решение маслихата города Семей области Абай от 20 ноября 2024 года № 34/177-VIII. Зарегистрировано Департаментом юстиции области Абай 27 ноября 2024 года № 379-18
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2024 год по городу Семей
  kaz: Семей қаласы бойынша 2024 жылға арналған шетелдіктер үшін туристік жарнаның мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-20
approved_by:
- '168002000002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/203619/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203619/rus/20.11.2024
