act_code: '182195'
requisite: Решение маслихата района Ақсуат области Абай от 23 мая 2023 года № 4/11-VIII. Зарегистрировано Департаментом юстиции области Абай 29 мая 2023 года № 86-18. Утратило силу решением маслихата района Ақсуат области Абай от 5 декабря 2023 года № 8/4-VIII (вводится в действие по истечении десяти календарных дней после дня первого официального опубликования)
title:
  rus: Об утверждении Правил оказания социальной помощи, установления размеров и определения перечня отдельных категорий нуждающихся граждан района Аксуат
  kaz: Ақсуат ауданында әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-05-23
approved_by:
- '168004000002'
version_date:
  kaz: 2023-05-23
  rus: 2023-05-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/182195/kaz/23.05.2023
  rus: https://zan.gov.kz/client/#!/doc/182195/rus/23.05.2023
