act_code: '187801'
requisite: Решение Аягозского районного маслихата области Абай от 12 октября 2023 года № 7/93-VIII. Зарегистрировано Департаментом юстиции области Абай 1 ноября 2023 года № 140-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-12
approved_by:
- '168006000002'
version_date:
  kaz: 2023-10-12
  rus: 2023-10-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/187801/kaz/12.10.2023
  rus: https://zan.gov.kz/client/#!/doc/187801/rus/12.10.2023
