act_code: '187801'
requisite: Решение Аягозского районного маслихата области Абай от 12 октября 2023 года № 7/93-VIII. Зарегистрировано Департаментом юстиции области Абай 1 ноября 2023 года № 140-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-12
approved_by:
- '168006000002'
version_date:
  kaz: 2026-08-05
  rus: 2026-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/187801/kaz/05.08.2026
  rus: https://zan.gov.kz/client/#!/doc/187801/rus/05.08.2026
caused_by:
  code: '228608'
  requisite: Решение Аягозского районного маслихата области Абай от 5 августа 2026 года № 37/654-VIII
  title:
    rus: О внесении изменения в решение Аягозского районного маслихата от 12 октября 2023 года № 7/93-VІІІ «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Аягөз аудандық мәслихатының 2023 жылғы 12 қазандағы № 7/93-VIIІ «Әлеуметтiк көмек көрсетудiң, оның мөлшерлерiн белгiлеудiң және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228608/rus
