act_code: '187801'
requisite: Решение Аягозского районного маслихата области Абай от 12 октября 2023 года № 7/93-VIII. Зарегистрировано Департаментом юстиции области Абай 1 ноября 2023 года № 140-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-10-12
approved_by:
- '168006000002'
version_date:
  kaz: 2025-02-07
  rus: 2025-02-07
source:
  kaz: https://zan.gov.kz/client/#!/doc/187801/kaz/07.02.2025
  rus: https://zan.gov.kz/client/#!/doc/187801/rus/07.02.2025
caused_by:
  code: '207202'
  requisite: Решение Аягозского районного маслихата области Абай от 7 февраля 2025 года № 22/411-VIII. Зарегистрировано Департаментом юстиции области Абай 18 февраля 2025 года № 421-18
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 12 октября 2023 года № 7/93-VІІІ «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Аягөз аудандық мәслихатының 2023 жылғы 12 қазандағы № 7/93-VIIІ «Әлеуметтiк көмек көрсетудiң, оның мөлшерлерiн белгiлеудiң және мұқтаж азаматтардың жекелеген санаттарының тiзбесiн айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207202/rus
