act_code: '221095'
requisite: Решение маслихата района Жаңасемей области Абай от 29 декабря 2025 года № 25/303-VIII
title:
  rus: Об утверждении Плана по управлению пастбищами и их использованию по району Жаңасемей на 2026-2030 годы
  kaz: Жаңасемей ауданы бойынша жайылымдарды басқару және оларды пайдалану жөніндегі  2026-2030 жылдарға арналған жоспарды бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-29
approved_by:
- '168013000002'
version_date:
  kaz: 2025-12-29
  rus: 2025-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/221095/kaz/29.12.2025
  rus: https://zan.gov.kz/client/#!/doc/221095/rus/29.12.2025
