act_code: '171907'
requisite: Решение Бородулихинского районного маслихата области Абай от 20 сентября 2022 года № 21-6-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 21 сентября 2022 года № 29727
title:
  rus: Об утверждении положения о награждении Почетной грамотой Бородулихинского района
  kaz: Бородулиха ауданының Құрмет грамотасымен наградтау туралы ережені бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-20
approved_by:
- '16800800002'
version_date:
  kaz: 2022-09-20
  rus: 2022-09-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/171907/kaz/20.09.2022
  rus: https://zan.gov.kz/client/#!/doc/171907/rus/20.09.2022
