act_code: '205064'
requisite: Решение Бескарагайского районного маслихата области Абай от 25 декабря 2024 года № 25/2-VIII
title:
  rus: О бюджете Бескарагайского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Бесқарағай ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-25
approved_by:
- '168007000002'
version_date:
  kaz: 2025-12-18
  rus: 2025-12-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/205064/kaz/18.12.2025
  rus: https://zan.gov.kz/client/#!/doc/205064/rus/18.12.2025
caused_by:
  code: '219060'
  requisite: Решение Бескарагайского районного маслихата области Абай от 18 декабря 2025 года № 35/6-VIII
  title:
    rus: О внесении изменений в решение Бескарагайского районного маслихата от 25 декабря 2024 года № 25/2-VІІІ «О бюджете Бескарагайского района на 2025-2027 годы»
    kaz: Бесқарағай аудандық мәслихатының 2024 жылғы 25 желтоқсандағы № 25/2-VIII «2025-2027 жылдарға арналған Бесқарағай ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/219060/rus
