act_code: '203622'
requisite: Решение Урджарского районного маслихата области Абай от 25 ноября 2024 года № 20-384/VIII. Зарегистрировано Департаментом юстиции области Абай 27 ноября 2024 года № 378-18. Утратило силу решением Урджарского районного маслихата области Абай от 31 декабря 2025 года № 31-652/VIII (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Урджарском районе
  kaz: Үржар ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-11-25
approved_by:
- '168010000002'
version_date:
  kaz: 2024-11-25
  rus: 2024-11-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/203622/kaz/25.11.2024
  rus: https://zan.gov.kz/client/#!/doc/203622/rus/25.11.2024
