act_code: '171372'
requisite: Решение маслихата Абайского района области Абай от 8 сентября 2022 года № 27/3-VII. Утратило силу решением Абайского районного маслихата области Абай от 4 июля 2023 года № 4/7-VIIІ (вводится в действие по истечении десяти календарных дней после его первого официального опубликования)
title:
  rus: Об утверждении Правил проведения раздельных сходов местного сообщества на территории Абайского района
  kaz: Абай ауданының аумағында жергілікті қоғамдастықтың бөлек жиындарын өткізудің қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-09-08
approved_by:
- '168005000002'
version_date:
  kaz: 2022-09-08
  rus: 2022-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/171372/kaz/08.09.2022
  rus: https://zan.gov.kz/client/#!/doc/171372/rus/08.09.2022
