act_code: '177788'
requisite: Решение Урджарского районного маслихата области Абай от 29 декабря 2022 года № 22-393/VII. Утратило силу решением Урджарского районного маслихата области Абай от 26 декабря 2023 года № 9-222/VIII (вводится в действие с 01.01.2024)
title:
  rus: О бюджете Салкынбельского сельского округа Урджарского района на 2023-2025 годы
  kaz: Үржар ауданы Салқынбел ауылдық округінің 2023-2025 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-12-29
approved_by:
- '168010000002'
version_date:
  kaz: 2022-12-29
  rus: 2022-12-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/177788/kaz/29.12.2022
  rus: https://zan.gov.kz/client/#!/doc/177788/rus/29.12.2022
