act_code: '216561'
requisite: Решение Бородулихинского районного маслихата области Абай от 3 ноября 2025 года № 37-3-VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов по Бородулихинскому району
  kaz: Бородулиха ауданы бойынша коммуналдық қалдықтардың түзілу және жинақталу нормаларын бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2025-11-03
approved_by:
- '168008000002'
version_date:
  kaz: 2025-11-03
  rus: 2025-11-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/216561/kaz/03.11.2025
  rus: https://zan.gov.kz/client/#!/doc/216561/rus/03.11.2025
