act_code: '204917'
requisite: Решение Аягозского районного маслихата области Абай от 19 декабря 2024 года № 19/356-VIII. Зарегистрировано Департаментом юстиции области Абай 26 декабря 2024 года № 399-18
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Аягозского района
  kaz: Аягөз ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-19
approved_by:
- '168006000002'
version_date:
  kaz: 2025-04-29
  rus: 2025-04-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/204917/kaz/29.04.2025
  rus: https://zan.gov.kz/client/#!/doc/204917/rus/29.04.2025
caused_by:
  code: '209744'
  requisite: Решение Аягозского районного маслихата области Абай от 29 апреля 2025 года № 24/430-VIII. Зарегистрировано Департаментом юстиции области Абай 30 апреля 2025 года № 447-18
  title:
    rus: О внесении изменения в решение Аягозского районного маслихата от 19 декабря 2024 года № 19/356-VІІІ «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Аягозского района»
    kaz: Аягөз аудандық мәслихатының 2024 жылғы 19 желтоқсандағы № 19/356-VIII «Аягөз ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209744/rus
