act_code: '208645'
requisite: Решение Жарминского районного маслихата области Абай от 28 марта 2025 года № 23/435-VIII
title:
  rus: Об утверждении программы по управлению коммунальными отходами по Жарминскому району на 2025–2029 годы
  kaz: Жарма ауданы бойынша коммуналдық қалдықтарды басқару жөніндегі 2025–2029 жылдарға арналған бағдарламаны бекіту туралы
form: РЕШ
type_codes:
- ПРОГ
- РЕШ
approved_on: 2025-03-28
approved_by:
- '168009000002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/208645/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/208645/rus/28.03.2025
