act_code: '205861'
requisite: Решение Жарминского районного маслихата области Абай от 5 января 2025 года № 20/379-VIII
title:
  rus: О бюджете поселка Ауэзов Жарминского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Жарма ауданы Әуезов кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-05
approved_by:
- '168009000002'
version_date:
  kaz: 2025-02-27
  rus: 2025-02-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/205861/kaz/27.02.2025
  rus: https://zan.gov.kz/client/#!/doc/205861/rus/27.02.2025
caused_by:
  code: '207561'
  requisite: Решение Жарминского районного маслихата области Абай от 27 февраля 2025 года № 21/407-VIII
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 05 января 2025 года № 20/379-VIІI «О бюджете поселка Ауэзова Жарминского района на 2025-2027 годы»
    kaz: Жарма аудандық мәслихатының 2025 жылғы 05 қаңтардағы № 20/379-VIІI «2025-2027 жылдарға арналған Жарма ауданы Әуезов кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/207561/rus
