act_code: '205861'
requisite: Решение Жарминского районного маслихата области Абай от 5 января 2025 года № 20/379-VIII
title:
  rus: О бюджете поселка Ауэзов Жарминского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Жарма ауданы Әуезов кентінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-01-05
approved_by:
- '168009000002'
version_date:
  kaz: 2025-09-30
  rus: 2025-09-30
source:
  kaz: https://zan.gov.kz/client/#!/doc/205861/kaz/30.09.2025
  rus: https://zan.gov.kz/client/#!/doc/205861/rus/30.09.2025
caused_by:
  code: '214992'
  requisite: Решение Жарминского районного маслихата области Абай от 30 сентября 2025 года № 29/486-VIII
  title:
    rus: О внесении изменений в решение Жарминского районного маслихата от 05 января 2025 года № 20/379-VIІI «О бюджете поселка Ауэзова Жарминского района на 2025-2027 годы»
    kaz: Жарма аудандық мәслихатының 2025 жылғы 05 қаңтардағы № 20/379-VIІI «2025-2027 жылдарға арналған Жарма ауданы Әуезов кентінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/214992/rus
