act_code: '199356'
requisite: Решение маслихата района Жаңасемей области Абай от 22 июля 2024 года № 9/41-VIII
title:
  rus: О бюджете Кокентауского сельского округа района Жаңасемей области Абай на 2024-2026 годы
  kaz: Абай облысы Жаңасемей ауданы Көкентау ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-07-22
approved_by:
- '168013000002'
version_date:
  kaz: 2024-12-11
  rus: 2024-12-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/199356/kaz/11.12.2024
  rus: https://zan.gov.kz/client/#!/doc/199356/rus/11.12.2024
caused_by:
  code: '204461'
  requisite: Решение маслихата района Жаңасемей области Абай от 11 декабря 2024 года № 12/82-VIII
  title:
    rus: О внесении изменении в решение маслихата района Жаңасемей от 22 июля 2024 года № 9/41-VІII «О бюджете Кокентауского сельского округа района Жаңасемей на 2024-2026 годы»
    kaz: Жаңасемей аудандықмәслихатының 2024 жылғы 22 шілдедегі № 9/41-VІII «Абай облысы Жаңасемей ауданы Көкентау ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/204461/rus
