act_code: '206423'
requisite: Решение Абайского районного маслихата области Абай от 31 декабря 2024 года № 24/7-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/7-VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Каскабулакского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Қасқабұлақ ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '168005000002'
version_date:
  kaz: 2024-12-31
  rus: 2024-12-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/206423/kaz/31.12.2024
  rus: https://zan.gov.kz/client/#!/doc/206423/rus/31.12.2024
