act_code: '195489'
requisite: Решение акима Аягозского района области Абай от 27 марта 2024 года № 1. Зарегистрировано Департаментом юстиции области Абай 10 апреля 2024 года № 254-18
title:
  rus: Об образовании избирательных участков Аягозского района
  kaz: Аягөз ауданының сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-27
approved_by:
- '168006000003'
version_date:
  kaz: 2024-03-27
  rus: 2024-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/195489/kaz/27.03.2024
  rus: https://zan.gov.kz/client/#!/doc/195489/rus/27.03.2024
