act_code: '191448'
requisite: Решение Абайского районного маслихата области Абай от 28 декабря 2023 года № 12/8-VIII. Утратило силу решением Абайского районного маслихата области Абай от 31 декабря 2024 года № 24/8-VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Медеуского сельского округа на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Медеу ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-28
approved_by:
- '168005000002'
version_date:
  kaz: 2023-12-28
  rus: 2023-12-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/191448/kaz/28.12.2023
  rus: https://zan.gov.kz/client/#!/doc/191448/rus/28.12.2023
