act_code: '191405'
requisite: Решение маслихата города Семей области Абай от 26 декабря 2023 года № 17/104-VIII. Отменено решением маслихата города Семей области Абай от 25 июня 2024 года № 27/148-VIII (вводится в действие с момента подписания)
title:
  rus: «О бюджете сельских округов и поселков на 2024-2026 годы»
  kaz: «Ауылдық округтер мен кенттердің 2024-2026 жылдарға арналған бюджеті туралы»
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '168002000002'
version_date:
  kaz: 2024-06-18
  rus: 2024-06-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/191405/kaz/18.06.2024
  rus: https://zan.gov.kz/client/#!/doc/191405/rus/18.06.2024
caused_by:
  code: '197872'
  requisite: Решение маслихата города Семей области Абай от 18 июня 2024 года № 26/144-VIII. Отменено решением маслихата города Семей области Абай от 25 июня 2024 года № 27/148-VIII (вводится в действие с момента подписания)
  title:
    rus: О внесении изменений в решение маслихата города Семей от 26 декабря 2023 года № 17/104-VIII «О бюджете сельских округов и поселков на 2024-2026 годы»
    kaz: Семей қаласы мәслихатының 2023 жылғы 26 желтоқсандағы № 17/104-VIII «Ауылдық округтер мен кенттердің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/197872/rus
