act_code: '221774'
requisite: Решение маслихата области Абай от 29 января 2026 года № 34/228-VIII
title:
  rus: Об утверждении размера платы за один кубический метр питьевой воды, поданной из систем водоснабжения, включённых в перечень систем водоснабжения, стоимость услуг по подаче питьевой воды которых подлежит субсидированию по области Абай
  kaz: Абай облысында ауызсу беру бойынша көрсетілетін қызметтердің құны субсидиялауға жататын сумен жабдықтау жүйелерінің тізбесіне енгізілген сумен жабдықтау жүйелерінен берілген ауызсудың бір текше метрі үшін төлемақы мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-01-29
approved_by:
- '168000000002'
version_date:
  kaz: 2026-01-29
  rus: 2026-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/221774/kaz/29.01.2026
  rus: https://zan.gov.kz/client/#!/doc/221774/rus/29.01.2026
