act_code: '192490'
requisite: Решение Курчатовского городского маслихата области Абай от 27 декабря 2023 года № 14/84-VIII. Зарегистрировано Департаментом юстиции области Абай 11 января 2024 года № 207-18. Утратило силу решением Курчатовского городского маслихата области Абай от 19 декабря 2024 года № 24/147-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2023-12-27
approved_by:
- '168003000002'
version_date:
  kaz: 2023-12-27
  rus: 2023-12-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/192490/kaz/27.12.2023
  rus: https://zan.gov.kz/client/#!/doc/192490/rus/27.12.2023
