act_code: '219527'
requisite: Решение маслихата района Мақаншы области Абай от 22 декабря 2025 года № 31-225/VIII
title:
  rus: О бюджете Каратальского сельского округа района Мақаншы на 2026-2028 годы
  kaz: Мақаншы ауданы Қаратал ауылдық округінің 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-22
approved_by:
- '168012000002'
version_date:
  kaz: 2026-04-24
  rus: 2026-04-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/219527/kaz/24.04.2026
  rus: https://zan.gov.kz/client/#!/doc/219527/rus/24.04.2026
caused_by:
  code: '224590'
  requisite: Решение маслихата района Мақаншы области Абай от 24 апреля 2026 года № 37-250/VIII
  title:
    rus: О внесении изменений в решение маслихата района Мақаншы от 22 декабря 2025 года № 31-225/VIII «О бюджете Каратальского сельского округа района Мақаншы на 2026-2028 годы»
    kaz: Мақаншы ауданы маслихатының 2025 жылғы 22 желтоқсандағы № 31-225/VIII «Мақаншы ауданы Қаратал ауылдық округінің 2026-2028 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224590/rus
