act_code: '200315'
requisite: Решение маслихата района Жаңасемей области Абай от 28 августа 2024 года № 10/52-VIII. Зарегистрировано Департаментом юстиции области Абай 3 сентября 2024 года № 322-18
title:
  rus: Об определении размера и порядка оказания жилищной помощи в районе Жаңасемей
  kaz: Жаңасемей ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-08-28
approved_by:
- '168013000002'
version_date:
  kaz: 2024-08-28
  rus: 2024-08-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/200315/kaz/28.08.2024
  rus: https://zan.gov.kz/client/#!/doc/200315/rus/28.08.2024
