act_code: '182668'
requisite: Решение акима города Семей области Абай от 8 июня 2023 года № 4. Утратило силу решением акима города Семей области Абай от 28 июля 2023 года № 5 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации природного характера в связи с возникновением пожара на территории государственного лесного природного резервата «Семей орманы» города Семей области Абай
  kaz: Абай облысы Семей қаласының «Семей орманы» мемлекеттік орман табиғи резерватының (Батпаев орманшылығы 66, 67, 55, 42 кварталдарда) аумағында өрттің шығуына байланысты табиғи сипаттағы төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-06-08
approved_by:
- '168002000003'
version_date:
  kaz: 2023-06-08
  rus: 2023-06-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/182668/kaz/08.06.2023
  rus: https://zan.gov.kz/client/#!/doc/182668/rus/08.06.2023
