act_code: '174349'
requisite: Решение маслихата района Аксуат области Абай от 9 ноября 2022 года № 10/6-VII
title:
  rus: О бюджете Кумкольского сельского округа района Аксуат на 2022 -2024 годы
  kaz: 2022-2024 жылдарға арналған Ақсуат ауданы Құмкөл ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-09
approved_by:
- '168004000002'
version_date:
  kaz: 2022-11-09
  rus: 2022-11-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/174349/kaz/09.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174349/rus/09.11.2022
