act_code: '193845'
requisite: Решение Курчатовского городского маслихата области Абай от 21 февраля 2024 года № 15/88-VIII. Зарегистрировано Департаментом юстиции области Абай 29 февраля 2024 года № 229-18
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в городе Курчатов
  kaz: Курчатов қаласында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-21
approved_by:
- '168003000002'
version_date:
  kaz: 2024-02-21
  rus: 2024-02-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/193845/kaz/21.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193845/rus/21.02.2024
