act_code: '223806'
requisite: Решение маслихата города Семей области Абай от 31 марта 2026 года № 55/295-VIII
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2026 год по городу Семей
  kaz: Семей қаласы бойынша 2026 жылға арналған шетелдіктер үшін туристік жарнаның мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2026-03-31
approved_by:
- '168002000002'
version_date:
  kaz: 2026-03-31
  rus: 2026-03-31
source:
  kaz: https://zan.gov.kz/client/#!/doc/223806/kaz/31.03.2026
  rus: https://zan.gov.kz/client/#!/doc/223806/rus/31.03.2026
