act_code: '197038'
requisite: Решение Бородулихинского районного маслихата области Абай от 17 мая 2024 года № 17-4-VIII. Зарегистрировано Департаментом юстиции области Абай 24 мая 2024 года № 282-18
title:
  rus: Об утверждении ставок туристского взноса для иностранцев либо физических или юридических лиц, оплачивающих проживание иностранца (приглашающая сторона, туроператор) по Бородулихинскому району
  kaz: Бородулиха ауданы бойынша шетелдіктер немесе шетелдіктің тұруына ақы төлейтін жеке немесе заңды тұлғалар (шақырушы тарап, туроператор) үшін туристік жарна мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-05-17
approved_by:
- '16800800002'
version_date:
  kaz: 2024-05-17
  rus: 2024-05-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/197038/kaz/17.05.2024
  rus: https://zan.gov.kz/client/#!/doc/197038/rus/17.05.2024
