act_code: '194045'
requisite: Решение акима Жарминского района области Абай от 6 марта 2024 года № 7
title:
  rus: О признании утратившим силу решения акима Жарминского района области Абай от 16 февраля 2024 года № 5 «Об объявлении чрезвычайной ситуации»
  kaz: Абай облысы Жарма ауданы әкімінің 2024 жылғы 16 ақпандағы № 5 «Төтенше жағдайды жариялау туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-06
approved_by:
- '168009000003'
version_date:
  kaz: 2024-03-06
  rus: 2024-03-06
source:
  kaz: https://zan.gov.kz/client/#!/doc/194045/kaz/06.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194045/rus/06.03.2024
