act_code: '220316'
requisite: Решение Аягозского районного маслихата области Абай от 23 декабря 2025 года № 31/571-VIII
title:
  rus: О бюджете Емелтауского сельского округа Аягозского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Аягөз ауданының Емелтау ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '168006000002'
version_date:
  kaz: 2026-07-16
  rus: 2026-07-16
source:
  kaz: https://zan.gov.kz/client/#!/doc/220316/kaz/16.07.2026
  rus: https://zan.gov.kz/client/#!/doc/220316/rus/16.07.2026
caused_by:
  code: '227989'
  requisite: Решение Аягозского районного маслихата области Абай от 16 июля 2026 года № 35/641-VIII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 23 декабря 2025 года №31/571-VІIІ «О бюджете Емелтауского сельского округа Аягозского района на 2026-2028 годы»
    kaz: Аягөз аудандық мәслихатының 2025 жылғы 23 желтоқсандағы №31/571-VІІІ «2026-2028 жылдарға арналған Аягөз ауданының Емелтау ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/227989/rus
