act_code: '210788'
requisite: Решение Кокпектинского районного маслихата области Абай от 19 мая 2025 года № 27-2. Зарегистрировано Департаментом юстиции области Абай 27 мая 2025 года № 460-18
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-05-19
approved_by:
- '168011000002'
version_date:
  kaz: 2026-08-26
  rus: 2026-08-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/210788/kaz/26.08.2026
  rus: https://zan.gov.kz/client/#!/doc/210788/rus/26.08.2026
caused_by:
  code: '229524'
  requisite: Решение Кокпектинского районного маслихата области Абай от 26 августа 2026 года № 46-3/1
  title:
    rus: О внесении изменений и дополнения в решение Кокпектинского районного маслихата от 19 мая 2025 года № 27-2«Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Көкпекті аудандық мәслихатының 2025 жылғы 19 мамырдағы № 27-2 «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер мен толықтыру енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/229524/rus
