act_code: '198455'
requisite: Решение маслихата города Семей области Абай от 28 июня 2024 года № 28/153-VIII. Зарегистрировано Департаментом юстиции области Абай 3 июля 2024 года № 297-18
title:
  rus: Об установлении категории автостоянок (паркингов) и увеличении базовых ставок налога на земли, выделенные под автостоянки (паркинги) по городу Семей области Абай
  kaz: Абай облысы Семей қаласы бойынша автотұрақтардың (паркингтердің) санаттарын белгілеу және автотұрақтарға (паркингтерге) бөлінген жерлерге базалық салықтық мөлшерлемелерін ұлғайту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-06-28
approved_by:
- '168002000002'
version_date:
  kaz: 2024-06-28
  rus: 2024-06-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/198455/kaz/28.06.2024
  rus: https://zan.gov.kz/client/#!/doc/198455/rus/28.06.2024
