act_code: '189229'
requisite: Решение маслихата города Семей области Абай от 17 ноября 2023 года № 13/78-VIII. Зарегистрировано Департаментом юстиции области Абай 29 ноября 2023 года № 165-18
title:
  rus: Об утверждении проекта (схемы) зонирования земель города Семей области Абай
  kaz: Абай облысы Семей қаласының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2023-11-17
approved_by:
- '168002000002'
version_date:
  kaz: 2023-11-17
  rus: 2023-11-17
source:
  kaz: https://zan.gov.kz/client/#!/doc/189229/kaz/17.11.2023
  rus: https://zan.gov.kz/client/#!/doc/189229/rus/17.11.2023
