act_code: '189229'
requisite: Решение маслихата города Семей области Абай от 17 ноября 2023 года № 13/78-VIII. Зарегистрировано Департаментом юстиции области Абай 29 ноября 2023 года № 165-18
title:
  rus: Об утверждении проекта (схемы) зонирования земель города Семей области Абай
  kaz: Абай облысы Семей қаласының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту туралы
form: РЕШ
type_codes:
- РЕШ
- СХЕМ
approved_on: 2023-11-17
approved_by:
- '168002000002'
version_date:
  kaz: 2024-11-20
  rus: 2024-11-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/189229/kaz/20.11.2024
  rus: https://zan.gov.kz/client/#!/doc/189229/rus/20.11.2024
caused_by:
  code: '202996'
  requisite: Решение маслихата города Семей области Абай от 20 ноября 2024 года № 34/178-VIII. Зарегистрировано Департаментом юстиции области Абай 21 ноября 2024 года № 372-18
  title:
    rus: О внесении изменений в решение маслихата города Семей области Абай от 17 ноября 2023 года № 13/78-VIII «Об утверждении проекта (схемы) зонирования земель города Семей области Абай»
    kaz: Абай облысы Семей қаласы мәслихатының 2023 жылғы 17 қарашадағы № 13/78-VIII «Абай облысы Семей қаласының жерлерін аймақтарға бөлу жобасын (схемасын) бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202996/rus
