act_code: '200829'
requisite: Решение акима района Мақаншы области Абай от 11 сентября 2024 года № 1. Зарегистрировано Департаментом юстиции области Абай 19 сентября 2024 года № 335-18
title:
  rus: Об образовании избирательных участков на территории района Мақаншы
  kaz: Мақаншы ауданының аумағында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-09-11
approved_by:
- '168012000003'
version_date:
  kaz: 2026-02-12
  rus: 2026-02-12
source:
  kaz: https://zan.gov.kz/client/#!/doc/200829/kaz/12.02.2026
  rus: https://zan.gov.kz/client/#!/doc/200829/rus/12.02.2026
caused_by:
  code: '222123'
  requisite: Решение акима района Мақаншы области Абай от 12 февраля 2026 года № 1
  title:
    rus: О внесении изменения в решение акима района Мақаншы от 11 сентября 2024 года № 1 «Об образовании избирательных участков на территории района Мақаншы»
    kaz: Мақаншы ауданы әкімінің 2024 жылғы 11 қыркүйектегі № 1 «Мақаншы ауданының аумағында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222123/rus
