act_code: '199685'
requisite: Решение акима района Жаңасемей области Абай от 9 августа 2024 года № 1. Зарегистрировано Департаментом юстиции области Абай 12 августа 2024 года № 310-18
title:
  rus: Об образовании избирательных участков в районе Жаңасемей
  kaz: Жаңасемей ауданында сайлау учаскелерін құру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-08-09
approved_by:
- '168013000003'
version_date:
  kaz: 2026-02-23
  rus: 2026-02-23
source:
  kaz: https://zan.gov.kz/client/#!/doc/199685/kaz/23.02.2026
  rus: https://zan.gov.kz/client/#!/doc/199685/rus/23.02.2026
caused_by:
  code: '222378'
  requisite: Решение акима района Жаңасемей области Абай от 23 февраля 2026 года № 1
  title:
    rus: О внесении изменения в решение акима района Жаңасемей области Абай от 9 августа 2024 года № 1 «Об образовании избирательных участков в районе Жаңасемей»
    kaz: Абай облысы Жаңасемей ауданы әкімінің 2024 жылғы 9 тамыздағы № 1 «Жаңасемей ауданында сайлау учаскелерін құру туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/222378/rus
