act_code: '215980'
requisite: Решение маслихата района Жаңасемей области Абай от 21 октября 2025 года № 21/230-VIII
title:
  rus: Об утверждении норм образования и накопления коммунальных отходов, тарифов на сбор, транспортировку, сортировку и захоронение твердых бытовых отходов по району Жаңасемей
  kaz: Жаңасемей ауданы бойынша коммуналдық қалдықтардын түзілу және жинақталу нормаларын, тұрмыстық қатты қалдықтарды жинауға, тасымалдауға, сұрыптауға және көмуге арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- НОРМ
- РЕШ
approved_on: 2025-10-21
approved_by:
- '168013000002'
version_date:
  kaz: 2025-10-21
  rus: 2025-10-21
source:
  kaz: https://zan.gov.kz/client/#!/doc/215980/kaz/21.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215980/rus/21.10.2025
