act_code: '202873'
requisite: Решение маслихата района Мақаншы области Абай от 8 ноября 2024 года № 13-83/VIII. Зарегистрировано Департаментом юстиции области Абай 18 ноября 2024 года № 370-18
title:
  rus: Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в районе Мақаншы
  kaz: Мақаншы ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы
form: РЕШ
type_codes:
- ПОР
- РЕШ
approved_on: 2024-11-08
approved_by:
- '168012000002'
version_date:
  kaz: 2025-03-27
  rus: 2025-03-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/202873/kaz/27.03.2025
  rus: https://zan.gov.kz/client/#!/doc/202873/rus/27.03.2025
caused_by:
  code: '209616'
  requisite: Решение маслихата района Мақаншы области Абай от 27 марта 2025 года № 18-122/VIII. Зарегистрировано Департаментом юстиции области Абай 29 апреля 2025 года № 446-18
  title:
    rus: О внесении изменения в решение маслихата района Мақаншы от 8 ноября 2024 года № 13-83/VIIІ «Об определении порядка и размера возмещения затрат на обучение на дому детей с ограниченными возможностями из числа детей с инвалидностью по индивидуальному учебному плану в районе Мақаншы»
    kaz: Мақаншы ауданы мәслихатының 2024 жылғы 8 қарашадағы № 13-83/VIIІ «Мақаншы ауданында мүгедектігі бар балалар қатарындағы кемтар балаларды жеке оқыту жоспары бойынша үйде оқытуға жұмсаған шығындарын өндіріп алу тәртібі мен мөлшерін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209616/rus
