act_code: '206219'
requisite: Решение Бородулихинского районного маслихата области Абай от 30 декабря 2024 года № 28-14-VIII
title:
  rus: О бюджете Новошульбинского сельского округа Бородулихинского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Бородулиха ауданы Новошульба ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168008000002'
version_date:
  kaz: 2025-07-09
  rus: 2025-07-09
source:
  kaz: https://zan.gov.kz/client/#!/doc/206219/kaz/09.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206219/rus/09.07.2025
caused_by:
  code: '212289'
  requisite: Решение Бородулихинского районного маслихата области Абай от 9 июля 2025 года № 34-13-VIII
  title:
    rus: О внесении изменений в решение Бородулихинского районного маслихата от 30 декабря 2024 года № 28-14-VIII «О бюджете Новошульбинского сельского округа Бородулихинского района на 2025-2027 годы»
    kaz: Бородулиха аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 28-14-VIII «2025-2027 жылдарға арналған Бородулиха ауданы Новошульба ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212289/rus
