act_code: '206285'
requisite: Решение Аягозского районного маслихата области Абай от 30 декабря 2024 года № 20/400-VIII
title:
  rus: О бюджете Малкельдинского сельского округа Аягозского района на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Аягөз ауданының Малкелді ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-30
approved_by:
- '168006000002'
version_date:
  kaz: 2025-07-14
  rus: 2025-07-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/206285/kaz/14.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206285/rus/14.07.2025
caused_by:
  code: '212536'
  requisite: Решение Аягозского районного маслихата области Абай от 14 июля 2025 года № 27/481-VIII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 30 декабря 2024 года № 20/400-VІІI «О бюджете Малкельдинского сельского округа Аягозского района на 2025-2027 годы»
    kaz: Аягөз аудандық мәслихатының 2024 жылғы 30 желтоқсандағы № 20/400-VІІІ «2025-2027 жылдарға арналған Аягөз ауданының Малкелді ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212536/rus
