act_code: '210784'
requisite: Решение Курчатовского городского маслихата области Абай от 22 мая 2025 года № 27/176-VIII. Зарегистрировано Департаментом юстиции области Абай 27 мая 2025 года № 459-18
title:
  rus: Об утверждении Правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан города Курчатов
  kaz: Курчатов қаласының әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2025-05-22
approved_by:
- '168003000002'
version_date:
  kaz: 2025-05-22
  rus: 2025-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/210784/kaz/22.05.2025
  rus: https://zan.gov.kz/client/#!/doc/210784/rus/22.05.2025
