act_code: '204198'
requisite: Решение маслихата района Мақаншы области Абай от 26 ноября 2024 года № 14-89/VIII. Зарегистрировано Департаментом юстиции области Абай 17 декабря 2024 года № 389-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-11-26
approved_by:
- '168012000002'
version_date:
  kaz: 2025-05-22
  rus: 2025-05-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/204198/kaz/22.05.2025
  rus: https://zan.gov.kz/client/#!/doc/204198/rus/22.05.2025
caused_by:
  code: '211000'
  requisite: Решение маслихата района Мақаншы области Абай от 22 мая 2025 года № 21-138/VIII. Зарегистрировано Департаментом юстиции области Абай 3 июня 2025 года № 467-18
  title:
    rus: О внесении изменений в решение маслихата района Мақаншы от 26 ноября 2024 года № 14-89/VIII «Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан»
    kaz: Мақаншы ауданы мәслихатының 2024 жылғы 26 қарашадағы № 14-89/VIII «Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/211000/rus
