act_code: '204198'
requisite: Решение маслихата района Мақаншы области Абай от 26 ноября 2024 года № 14-89/VIII. Зарегистрировано Департаментом юстиции области Абай 17 декабря 2024 года № 389-18
title:
  rus: Об утверждении правил оказания социальной помощи, установления ее размеров и определения перечня отдельных категорий нуждающихся граждан
  kaz: Әлеуметтік көмек көрсетудің, оның мөлшерлерін белгілеудің және мұқтаж азаматтардың жекелеген санаттарының тізбесін айқындаудың қағидаларын бекіту туралы
form: РЕШ
type_codes:
- ПРАВ
- РЕШ
approved_on: 2024-11-26
approved_by:
- '168012000002'
version_date:
  kaz: 2024-11-26
  rus: 2024-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/204198/kaz/26.11.2024
  rus: https://zan.gov.kz/client/#!/doc/204198/rus/26.11.2024
