act_code: '192013'
requisite: Решение Урджарского районного маслихата области Абай от 26 декабря 2023 года № 9-195/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
title:
  rus: О бюджете Акжарского сельского округа Урджарского района на 2024-2026 годы
  kaz: Үржар ауданы Ақжар ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-26
approved_by:
- '168010000002'
version_date:
  kaz: 2024-04-25
  rus: 2024-04-25
source:
  kaz: https://zan.gov.kz/client/#!/doc/192013/kaz/25.04.2024
  rus: https://zan.gov.kz/client/#!/doc/192013/rus/25.04.2024
caused_by:
  code: '196342'
  requisite: Решение Урджарского районного маслихата области Абай от 25 апреля 2024 года № 14-258/VIII. Утратило силу решением Урджарского районного маслихата области Абай от 24 декабря 2024 года № 21-410/VIII (вводится в действие с 01.01.2025)
  title:
    rus: О внесении изменения в решение Урджарского районного маслихата от 26 декабря 2023 года № 9-195/VIIІ «О бюджете Акжарского сельского округа Урджарского района на 2024-2026 годы»
    kaz: Үржар аудандық мәслихатының 2023 жылғы 26 желтоқсандағы № 9-195/VIII «Үржар ауданы Ақжар ауылдық округінің 2024-2026 жылдарға арналған бюджеті туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/196342/rus
