act_code: '219632'
requisite: Решение Аягозского районного маслихата области Абай от 18 декабря 2025 года № 31/560-VIII
title:
  rus: О бюджете Аягозского района на 2026-2028 годы
  kaz: 2026-2028 жылдарға арналған Аягөз ауданының бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-18
approved_by:
- '168006000002'
version_date:
  kaz: 2026-08-05
  rus: 2026-08-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/219632/kaz/05.08.2026
  rus: https://zan.gov.kz/client/#!/doc/219632/rus/05.08.2026
caused_by:
  code: '228606'
  requisite: Решение Аягозского районного маслихата области Абай от 5 августа 2026 года № 37/655-VIII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 18 декабря 2025 года № 31/560-VIІI «О бюджете Аягозского района на 2026-2028 годы»
    kaz: Аягөз аудандық мәслихатының 2025 жылғы 18 желтоқсандағы № 31/560-VIII «2026-2028 жылдарға арналған Аягөз ауданының бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/228606/rus
