act_code: '188485'
requisite: Решение Урджарского районного маслихата области Абай от 27 октября 2023 года № 6-145/VIII. Зарегистрировано Департаментом юстиции области Абай 17 ноября 2023 года № 151-18
title:
  rus: Об утверждении ставок туристского взноса для иностранцев либо физических или юридических лиц, оплачивающих проживание иностранца (приглашающая сторона, туроператор) по Урджарскому району
  kaz: Үржар ауданы бойынша шетелдіктер немесе шетелдіктің тұруына ақы төлейтін жеке немесе заңды тұлғалар (шақырушы тарап, туроператор) туристік жарнасын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-27
approved_by:
- '168010000002'
version_date:
  kaz: 2023-10-27
  rus: 2023-10-27
source:
  kaz: https://zan.gov.kz/client/#!/doc/188485/kaz/27.10.2023
  rus: https://zan.gov.kz/client/#!/doc/188485/rus/27.10.2023
