act_code: '190885'
requisite: Решение Абайского районного маслихата области Абай от 22 декабря 2023 года № 11/7-VIII. Зарегистрировано Департаментом юстиции области Абай 26 декабря 2023 года № 199-18. Утратило силу решением Абайского районного маслихата области Абай от 12 апреля 2024 года № 15/12-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и порядка оказания жилищной помощи в Абайском районе
  kaz: Абай ауданында тұрғын үй көмегін көрсетудің мөлшері мен тәртібін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-22
approved_by:
- '168005000002'
version_date:
  kaz: 2023-12-22
  rus: 2023-12-22
source:
  kaz: https://zan.gov.kz/client/#!/doc/190885/kaz/22.12.2023
  rus: https://zan.gov.kz/client/#!/doc/190885/rus/22.12.2023
