act_code: '194673'
requisite: Решение акима Жарминского района области Абай от 20 марта 2024 года № 8
title:
  rus: О признании утратившим силу решения акима Жарминского района области Абай от 21 февраля 2024 года № 6 «Об объявлении чрезвычайной ситуации»
  kaz: Абай облысы Жарма ауданы әкімінің 2024 жылғы 21 ақпандағы № 6 «Төтенше жағдайды жариялау туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-20
approved_by:
- '168009000003'
version_date:
  kaz: 2024-03-20
  rus: 2024-03-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/194673/kaz/20.03.2024
  rus: https://zan.gov.kz/client/#!/doc/194673/rus/20.03.2024
