act_code: '206419'
requisite: Решение Абайского районного маслихата области Абай от 31 декабря 2024 года № 24/9-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/9-VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Саржалского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Саржал ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '168005000002'
version_date:
  kaz: 2025-07-24
  rus: 2025-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/206419/kaz/24.07.2025
  rus: https://zan.gov.kz/client/#!/doc/206419/rus/24.07.2025
caused_by:
  code: '212799'
  requisite: Решение Абайского районного маслихата области Абай от 24 июля 2025 года № 30/8-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/9-VIII (вводится в действие с 01.01.2026)
  title:
    rus: О внесении изменений в решение маслихата от 31 декабря 2024 года № 24/9-VІIІ «О бюджете Саржалского сельского округа на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 31 желтоқсандағы № 24/9-VІIІ «2025-2027 жылдарға арналған Саржал ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/212799/rus
