act_code: '193799'
requisite: Решение маслихата области Абай от 20 февраля 2024 года № 13/95-VIII. Зарегистрировано Департаментом юстиции области Абай 28 февраля 2024 года № 226-18
title:
  rus: Об утверждении границ оценочных зон и поправочных коэффициентов к базовым ставкам платы за земельные участки в городе Семей области Абай
  kaz: Абай облысының Семей қаласындағы бағалау аймақтарының шекаралары және жер учаскелері үшін төлемақының базалық ставкаларына түзету коэффициенттерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-02-20
approved_by:
- '168000000002'
version_date:
  kaz: 2024-02-20
  rus: 2024-02-20
source:
  kaz: https://zan.gov.kz/client/#!/doc/193799/kaz/20.02.2024
  rus: https://zan.gov.kz/client/#!/doc/193799/rus/20.02.2024
