act_code: '192660'
requisite: Решение Жарминского районного маслихата области Абай от 5 января 2024 года № 10/206-VIII. Зарегистрировано Департаментом юстиции области Абай 16 января 2024 года № 210-18
title:
  rus: Об утверждении Положения о награждении Почетной грамотой Жарминского района
  kaz: Жарма ауданының Құрмет грамотасымен наградтау туралы Ережені бекіту туралы
form: РЕШ
type_codes:
- ПОЛ
- РЕШ
approved_on: 2024-01-05
approved_by:
- '168009000002'
version_date:
  kaz: 2024-01-05
  rus: 2024-01-05
source:
  kaz: https://zan.gov.kz/client/#!/doc/192660/kaz/05.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192660/rus/05.01.2024
