act_code: '220235'
requisite: Решение маслихата района Жаңасемей области Абай от 23 декабря 2025 года № 24/294-VIII
title:
  rus: О бюджете Приречного сельского округа района Жаңасемей на 2025-2027 годы
  kaz: Абай облысы Жаңасемей ауданы Приречный ауылдық округінің 2026-2028 жылдарға арналған бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-23
approved_by:
- '168013000002'
version_date:
  kaz: 2026-04-14
  rus: 2026-04-14
source:
  kaz: https://zan.gov.kz/client/#!/doc/220235/kaz/14.04.2026
  rus: https://zan.gov.kz/client/#!/doc/220235/rus/14.04.2026
caused_by:
  code: '224189'
  requisite: Решение маслихата района Жаңасемей области Абай от 14 апреля 2026 года № 27/330-VIII
  title:
    rus: О внесении изменений в решение маслихата района Жаңасемей области Абай от 23 декабря 2025 года № 24/294-VIII «О бюджете Приречного сельского округа на 2026-2028 годы»
    kaz: Абай облысы Жаңасемей аудандық мәслихатының 2025 жылғы 23 желтоқсандағы № 24/294-VIII «Абай облысы Жаңасемей ауданы Приречный ауылдық округінің 2026-2028 жылдарға арналған бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/224189/rus
