act_code: '195692'
requisite: Решение Абайского районного маслихата области Абай от 28 марта 2024 года № 14/8-VIII. Зарегистрировано Департаментом юстиции области Абай 16 апреля 2024 года № 256-18. Утратило силу решением Абайского районного маслихата области Абай от 7 октября 2025 года № 31/8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
title:
  rus: Об определении размера и перечня категорий получателей жилищных сертификатов по Абайскому району
  kaz: Абай ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-03-28
approved_by:
- '168005000002'
version_date:
  kaz: 2025-03-28
  rus: 2025-03-28
source:
  kaz: https://zan.gov.kz/client/#!/doc/195692/kaz/28.03.2025
  rus: https://zan.gov.kz/client/#!/doc/195692/rus/28.03.2025
caused_by:
  code: '209062'
  requisite: Решение Абайского районного маслихата области Абай от 28 марта 2025 года № 25/8-VIII. Зарегистрировано Департаментом юстиции области Абай 11 апреля 2025 года № 434-18. Утратило силу решением Абайского районного маслихата области Абай от 7 октября 2025 года № 31/8-VIII (вводится в действие по истечении десяти календарных дней после дня его первого официального опубликования)
  title:
    rus: О внесении изменения в решение Абайского районного маслихата от 28 марта 2024 года № 14/8-VІІІ «Об определении размера и перечня категорий получателей жилищных сертификатов по Абайскому району»
    kaz: Абай аудандық мәслихатының 2024 жылғы 28 наурыздағы № 14/8-VIIІ «Абай ауданы бойынша тұрғын үй сертификаттарының мөлшері мен оларды алушылар санаттарының тізбесін айқындау туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/209062/rus
