act_code: '218355'
requisite: Решение маслихата области Абай от 8 декабря 2025 года № 32/218-VIII
title:
  rus: Об утверждении ставок платы за пользование водными ресурсами поверхностных водных объектов области Абай
  kaz: Абай облысының жер үсті су объектілерінің су ресурстарын пайдаланғаны үшін төлемақы мөлшерлемелерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-12-08
approved_by:
- '168000000002'
version_date:
  kaz: 2025-12-08
  rus: 2025-12-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/218355/kaz/08.12.2025
  rus: https://zan.gov.kz/client/#!/doc/218355/rus/08.12.2025
