act_code: '174309'
requisite: Решение маслихата области Абай от 18 ноября 2022 года № 10/55-VII. Зарегистрировано в Министерстве юстиции Республики Казахстан 23 ноября 2022 года № 30682
title:
  rus: Об утверждении Правил содержания животных в области Абай
  kaz: Абай облысында жануарларды асырау қағидаларын бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2022-11-18
approved_by:
- '168000000002'
version_date:
  kaz: 2022-11-18
  rus: 2022-11-18
source:
  kaz: https://zan.gov.kz/client/#!/doc/174309/kaz/18.11.2022
  rus: https://zan.gov.kz/client/#!/doc/174309/rus/18.11.2022
