act_code: '215796'
requisite: Решение акима Кокпектинского сельского округа Кокпектинского района области Абай от 3 октября 2025 года № 1
title:
  rus: О Присвоение наименования новый улице расположенной по Кокпектинского сельского округа Кокпектинского района области Абай
  kaz: Абай облысы Көкпекті ауданы Көкпекті ауылдық округінің жаңа көшесіне «Көктерек» атауын беру туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-03
approved_by:
- '168011002002'
version_date:
  kaz: 2025-10-03
  rus: 2025-10-03
source:
  kaz: https://zan.gov.kz/client/#!/doc/215796/kaz/03.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215796/rus/03.10.2025
