act_code: '192964'
requisite: Решение Абайского районного маслихата области Абай от 29 января 2024 года № 13/2-VIII
title:
  rus: Об утверждении тарифов для населения на сбор и транспортировку твердых бытовых отходов по Абайскому району
  kaz: Абай ауданы бойынша халық үшін қатты тұрмыстық қалдықтарды жинауға және тасымалдауға арналған тарифтерді бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-01-29
approved_by:
- '168005000002'
version_date:
  kaz: 2024-01-29
  rus: 2024-01-29
source:
  kaz: https://zan.gov.kz/client/#!/doc/192964/kaz/29.01.2024
  rus: https://zan.gov.kz/client/#!/doc/192964/rus/29.01.2024
