act_code: '191843'
requisite: Решение Аягозского районного маслихата области Абай от 27 декабря 2023 года № 10/175-VIII
title:
  rus: О бюджете Акшаулинского сельского округа Аягозского района на 2024-2026 годы
  kaz: 2024-2026 жылдарға арналған Аягөз ауданының Ақшәулі ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-12-27
approved_by:
- '168006000002'
version_date:
  kaz: 2024-11-11
  rus: 2024-11-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/191843/kaz/11.11.2024
  rus: https://zan.gov.kz/client/#!/doc/191843/rus/11.11.2024
caused_by:
  code: '202740'
  requisite: Решение Аягозского районного маслихата области Абай от 11 ноября 2024 года № 17/308-VIII
  title:
    rus: О внесении изменений в решение Аягозского районного маслихата от 27 декабря 2023 года № 10/175-VIІI «О бюджете Акшаулинского сельского округа Аягозского района на 2024-2026 годы»
    kaz: Аягөз аудандық мәслихатының «2024-2026 жылдарға арналған Аягөз ауданының Ақшәулі ауылдық округінің бюджеті туралы» 2023 жылғы 27 желтоқсандағы № 10/175-VIІI шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202740/rus
