act_code: '206426'
requisite: Решение Абайского районного маслихата области Абай от 31 декабря 2024 года № 24/8-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/8-VIII (вводится в действие с 01.01.2026)
title:
  rus: О бюджете Медеуского сельского округа на 2025-2027 годы
  kaz: 2025-2027 жылдарға арналған Медеу ауылдық округінің бюджеті туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-12-31
approved_by:
- '168005000002'
version_date:
  kaz: 2025-05-26
  rus: 2025-05-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/206426/kaz/26.05.2025
  rus: https://zan.gov.kz/client/#!/doc/206426/rus/26.05.2025
caused_by:
  code: '210733'
  requisite: Решение Абайского районного маслихата области Абай от 26 мая 2025 года № 27/6-VIII. Утратило силу решением Абайского районного маслихата области Абай от 23 декабря 2025 года № 36/8-VIII (вводится в действие с 01.01.2026)
  title:
    rus: О внесении изменений в решение маслихата от 31 декабря 2024 года № 24/8-VIII «О бюджете Медеуского сельского округа на 2025-2027 годы»
    kaz: Мәслихаттың 2024 жылғы 31 желтоқсандағы № 24/8-VIII «2025-2027 жылдарға арналған Медеу ауылдық округінің бюджеті туралы» шешіміне өзгерістер енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/210733/rus
