act_code: '215731'
requisite: Решение Кокпектинского районного маслихата области Абай от 15 октября 2025 года № 32-5/7
title:
  rus: Об отмене решения Кокпектинского районного маслихата от 11 августа 2023 года № 5-3/1 «Об утверждении Методики оценки деятельности административных государственных служащих корпуса «Б» государственного учреждения «Аппарат Кокпектинского районного маслихата области Абай»
  kaz: Көкпекті аудандық мәслихатының 2023 жылғы 11 тамыздағы № 5-3/1 «Абай облысы Көкпекті аудандық мәслихатының аппараты» мемлекеттік мекемесінің «Б» корпусы мемлекеттiк әкiмшiлiк қызметшiлерiнiң қызметiн бағалаудың әдiстемесiн бекiту туралы» шешімінің күшін жою туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-10-15
approved_by:
- '168011000002'
version_date:
  kaz: 2025-10-15
  rus: 2025-10-15
source:
  kaz: https://zan.gov.kz/client/#!/doc/215731/kaz/15.10.2025
  rus: https://zan.gov.kz/client/#!/doc/215731/rus/15.10.2025
