act_code: '213215'
requisite: Решение акима Баркытбельского сельского округа Урджарского района области Абай от 11 августа 2025 года № 13
title:
  rus: О переименовании улиц села Баркытбел Баркытбельского сельского округа Урджарского района области Абай
  kaz: Абай облысы Үржар ауданы Барқытбел ауылдық округі Барқытбел ауылының көшелерін қайта атау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-08-11
approved_by:
- '168010025002'
version_date:
  kaz: 2025-08-11
  rus: 2025-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/213215/kaz/11.08.2025
  rus: https://zan.gov.kz/client/#!/doc/213215/rus/11.08.2025
