act_code: '212892'
requisite: Решение маслихата района Аксуат области Абай от 24 июля 2025 года № 31/11-VIII
title:
  rus: Об утверждении ставок туристского взноса для иностранцев на 2025 год по району Аксуат
  kaz: Ақсуат ауданы бойынша 2025 жылға арналған шетелдіктер үшін туристік жарнаның мөлшерлемесін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-07-24
approved_by:
- '168004000002'
version_date:
  kaz: 2025-07-24
  rus: 2025-07-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/212892/kaz/24.07.2025
  rus: https://zan.gov.kz/client/#!/doc/212892/rus/24.07.2025
