act_code: '187640'
requisite: Решение Бородулихинского районного маслихата области Абай от 6 октября 2023 года № 8-10-VIII. Зарегистрировано Департаментом юстиции области Абай 27 октября 2023 года № 138-18
title:
  rus: Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Бородулихинского района
  kaz: Бородулиха ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-10-06
approved_by:
- '16800800002'
version_date:
  kaz: 2024-10-24
  rus: 2024-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/187640/kaz/24.10.2024
  rus: https://zan.gov.kz/client/#!/doc/187640/rus/24.10.2024
caused_by:
  code: '202076'
  requisite: Решение Бородулихинского районного маслихата области Абай от 24 октября 2024 года № 23-5-VIII. Зарегистрировано Департаментом юстиции области Абай 29 октября 2024 года № 358-18
  title:
    rus: О внесении изменения в решение Бородулихинского районного маслихата от 6 октября 2023 года № 8-10-VIII «Об утверждении порядка и размера оказания социальной поддержки по оплате коммунальных услуг и приобретению топлива за счет бюджетных средств специалистам государственных организаций здравоохранения, социального обеспечения, образования, культуры, спорта и ветеринарии, проживающим и работающим в сельских населенных пунктах Бородулихинского района»
    kaz: Бородулиха аудандық мәслихатының 2023 жылғы 6 қазандағы № 8-10-VIII «Бородулиха ауданының ауылдық елді мекендерінде тұратын және жұмыс істейтін мемлекеттік денсаулық сақтау, әлеуметтік қамсыздандыру, білім беру, мәдениет, спорт және ветеринария ұйымдарының мамандарына бюджет қаражаты есебiнен коммуналдық көрсетілетін қызметтерге ақы төлеу және отын сатып алу бойынша әлеуметтік қолдау көрсету тәртібі мен мөлшерін бекіту туралы» шешіміне өзгеріс енгізу туралы
  link: https://zan.gov.kz/client/#!/doc/202076/rus
