act_code: '202082'
requisite: Решение Бородулихинского районного маслихата области Абай от 24 октября 2024 года № 23-3-VIII. Зарегистрировано Департаментом юстиции области Абай 29 октября 2024 года № 359-18. Утратило силу решением Бородулихинского районного маслихата области Абай от 23 декабря 2025 года № 42-21-VIII (вводится в действие с 01.01.2026)
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима розничного налога в Бородулихинском районе
  kaz: Бородулиха ауданында бөлшек салықтың арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2024-10-24
approved_by:
- '16800800002'
version_date:
  kaz: 2024-10-24
  rus: 2024-10-24
source:
  kaz: https://zan.gov.kz/client/#!/doc/202082/kaz/24.10.2024
  rus: https://zan.gov.kz/client/#!/doc/202082/rus/24.10.2024
