act_code: '184996'
requisite: Решение акима города Семей области Абай от 11 августа 2023 года № 8. Утратило силу решением акима города Семей области Абай от 19 июня 2024 года № 4 (вводится в действие со дня его первого официального опубликования)
title:
  rus: Об объявлении чрезвычайной ситуации техногенного характера объектового масштаба в котельной ГКП «Теплокоммунэнерго» города Семей области Абай
  kaz: Абай облысы Семей қаласының «Теплокоммунэнерго» МКК қазандығында техногендік сипаттағы объектілік масштабты төтенше жағдай жариялау туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2023-08-11
approved_by:
- '168002000003'
version_date:
  kaz: 2023-08-11
  rus: 2023-08-11
source:
  kaz: https://zan.gov.kz/client/#!/doc/184996/kaz/11.08.2023
  rus: https://zan.gov.kz/client/#!/doc/184996/rus/11.08.2023
