act_code: '214044'
requisite: Решение маслихата района Жаңасемей области Абай от 8 сентября 2025 года № 19/193-VIII
title:
  rus: Об утверждении регламента собрания местных сообществ поселка и сельских округов района Жаңасемей
  kaz: Жаңасемей ауданының кент және ауылдық округтерінің жергілікті қоғамдастық жиналысының регламентін бекіту туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-09-08
approved_by:
- '168013000002'
version_date:
  kaz: 2025-09-08
  rus: 2025-09-08
source:
  kaz: https://zan.gov.kz/client/#!/doc/214044/kaz/08.09.2025
  rus: https://zan.gov.kz/client/#!/doc/214044/rus/08.09.2025
