act_code: '217712'
requisite: Решение Абайского районного маслихата области Абай от 26 ноября 2025 года № 33/3-VIII
title:
  rus: О понижении размера ставки налогов при применении специального налогового режима на основе упрощенной декларации в Абайском районе
  kaz: Абай ауданында оңайлатылған декларация негізінде арнаулы салық режимін қолдану кезінде салық мөлшерлемесінің мөлшерін төмендету туралы
form: РЕШ
type_codes:
- РЕШ
approved_on: 2025-11-26
approved_by:
- '168005000002'
version_date:
  kaz: 2025-11-26
  rus: 2025-11-26
source:
  kaz: https://zan.gov.kz/client/#!/doc/217712/kaz/26.11.2025
  rus: https://zan.gov.kz/client/#!/doc/217712/rus/26.11.2025
